### ISSUE TITLE
Redis Broken Pipe Flaky Test

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#111]
The btp test's redis client fails with a broken pipe error:

https://circleci.com/workflow-run/33b5e57e-2a7b-4ee3-aca7-b5cfac5071b0

```
[2019-06-19T07:21:30Z ERROR interledger_store_redis::store] Error getting all accounts: Broken pipe (os error 32)
```

Found while investigating #110

**Comment by emschwartz** [comment]
Can this issue be closed now?
