### ISSUE TITLE
ImmutablePrepare w/ Bytes instead of BytesMut

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#114]
> We might want to think about adding a `Prepare.freeze()` method, or something like that that would turn it into an `ImmutablePrepare` backed by a `Bytes` instead of a `BytesMut`. In general, using a `BytesMut` enables us to do in-place updating of the `amount` and `expires_at`, but in this case it means we can't have a method that returns a slice of the data as a `Bytes` (that wouldn't require copying but would solve the lifetime issue)

cc @sentientwaffle

_Originally posted by @emschwartz in https://github.com/emschwartz/interledger-rs/pull/107_

**Comment by emschwartz** [comment]
We have a method that returns the `data` as a `&[u8]` so I think we can close this issue now
