### ISSUE TITLE
Strictly type Bearer Header

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#118]
Latest hyper added support for bearer headers: https://github.com/hyperium/hyper/blob/master/CHANGELOG.md
https://github.com/hyperium/hyper/commit/edf6ac2074d11694ded275807a66df3a8a8e33a6

In a few places, we use `auth[BEARER_TOKEN_START..]` syntax. This can cause the process that runs this line to crash, if the `auth` variable has length less than `BEARER_TOKEN_START`.

**Comment by dora-gt** [comment]
I think this could be closed now. It doesn't panic even if just `Bearer` is given.

@gakonst would you mind if I close this?
