### ISSUE TITLE
How often should we settle? 

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#121]
As title:

`settle_to` and `threshold` seem to me like user-set parameters, while `min_balance` should be set by the connector's operator (naming related issue #120)

There's no way for the user to enforce a certain settlement frequency since the node operator is the one who makes the call, but they can indicate their prefereance.

Right now we can treat it as operator set but we can think about it differently when we come up with the autopeering design (https://forum.interledger.org/t/auto-peering-easy-peering-and-open-signup/556)

**Comment by Neil-Jubinville** [comment]
Yes we should find a way for the frequency to be associated to the account so each account can register that value with the operator of the connector.   "requested_freq" 

I can see use cases where the buffering of money and synchronized settlement is useful.   I guess this is like cron for settlement from what I am thinking.

**Comment by emschwartz** [comment]
Closing this in favor of https://github.com/interledger-rs/interledger-rs/issues/229, which generalizes this feature
