### ISSUE TITLE
Remove `extern crate` directives since we are in Rust 2018

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#132]
> I am pretty sure you don't need all these `extern crate` directives in rust 2018.

https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html

_Originally posted by @zmanian in https://github.com/emschwartz/interledger-rs/pull/125_

**Comment by bstrie** [comment]
This is almost done; tower-web is a sticking point due to some deficiencies in its procedural macro expansions. See also #146

**Comment by emschwartz** [comment]
Can this be closed now?

**Comment by gakonst** [comment]
Let's keep this open until we replace tower-web with warp in the Settlement and Settlement Engines crates, for some reason doing [`use tower_web::impl_web` does not work. ](https://github.com/interledger-rs/interledger-rs/blob/0835049bebcdd0a4aceda1a1eba378ddde03ff70/crates/interledger-settlement-engines/src/api.rs#L25)

**Comment by bstrie** [comment]
This specific issue was fixed in #400, so I'll close this. Removing the tower_web dependency entirely can fall under #140.
