### ISSUE TITLE
CI Out of Memory when compiling crates

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#133]
As we've seen multiple times, CI does not have enough memory to compile everything. This has been temporarily fixed by reducing `codegen-units` as per @tarcieri's suggestion, but that's only a workaround, and will not be feasible if we keep adding crates. Is there a smarter way for us to compile the codebase?

ref:
https://internals.rust-lang.org/t/default-settings-for-parallel-codegen/519
https://vfoley.xyz/rust-compile-speed-tips/

The situation can probably be improved if we start using the same versions of crates everywhere

e.g.
https://circleci.com/gh/emschwartz/interledger-rs/644
https://circleci.com/gh/emschwartz/interledger-rs/640
https://circleci.com/gh/emschwartz/interledger-rs/639
https://circleci.com/gh/emschwartz/interledger-rs/637
.. and so on

**Comment by emschwartz** [comment]
We're using larger machines on CI for now and haven't run into this problem for a while. Hopefully some future refactors will reduce the memory required to compile the project but I think we can close this issue now
