### ISSUE TITLE
Statistics collection

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#139]
Node operators will want to collect statistics about:
- [x] Number of packets processed (maybe broken out by `Prepare`, `Fulfill`, `Reject`)
~~- [ ] Amount of money sent~~
~~- [ ] Node uptime~~
- [ ] Peer status

and potentially other things.

Should this kind of data be written to the store or exported using some external tool/API?

**Comment by gakonst** [comment]
https://github.com/pingcap/rust-prometheus could be used

**Comment by wliu** [comment]
In terms of metrics, definitely +1 on being able to export them. We're currently using Prometheus to do metrics aggregation for the `ilp-connector` implementation. @inthecloud247 for more feedback on this.

**Comment by emschwartz** [comment]
:+1: on using Prometheus. As far as how the metrics are collected, should they be output to a log or file or exposed via an HTTP endpoint on the API?

**Comment by wliu** [comment]
Exposed via HTTP would be totally reasonable and what `ilp-connector` does as well.

**Comment by emschwartz** [comment]
We should consider using https://github.com/metrics-rs/metrics, which is a metrics framework that provides a number of macros to work with as well as a prometheus-compatible exporter. It seems like a more flexible way to collect and expose metrics

**Comment by emschwartz** [comment]
After thinking about this more, I don't think it makes sense to use Prometheus for all of the stats mentioned in the initial issue.

- :+1: Number of packets processed
- :-1:  Amount of money sent 
  - This would need to be tracked separately for each currency and/or normalized across currencies
  - The amounts would need to be scaled (using a bignum library) because every account could have a different `asset_scale` (even for the same currency)
  - I'm not sure how `metrics-rs` handles overflowing counters (the sum of the values of ILP packets could easily exceed a `u64`) but it's probably not good
- :-1: Node uptime 
  - Seems like we can just track this with the logs
- :grey_question: Peer status
  - We could keep track of the results of sending route broadcasts to specific peers and use that as a proxy for whether the node is online or not (we probably want to do this only for `Peer` accounts)
  - Should this be tracked as a total of `peers_online` / `peers_offline` or should it be labeled by the peer's Account ID?

What do you think?
