### ISSUE TITLE
Migrate to std::future

### ISSUE THREAD

**Issue by bstrie** [interledger-rs/interledger-rs#142]
This module recently stabilized and is intended to be the long-term replacement for the futures crate. Pieces are being stabilized one at a time, so this will be an ongoing process. The most important piece to migrate is the first piece stabilized, `std::future::Future`, although as I run across our uses of the futures crate I will note them down here for eventual migration.

* [ ] futures::Future
* [ ] futures::future::Either
* [ ] futures::future::{err, ok, result}

**Comment by bstrie** [comment]
After exploring this a bit I think we'll want to wait a while longer until std::future percolates up through the rest of the async ecosystem, in order to avoid having to spend a lot of effort on compatibility shims that will eventually need to be torn out anyway. Let's reevaluate this in a month.

**Comment by bstrie** [comment]
Update: tokio, hyper, and hyper-tls all now feature support for std::future on their master branches. Will still want to wait for each of those to have their next official release, but this is an encouraging sign wrt timeframe.

**Comment by bstrie** [comment]
Update: tokio and hyper now both have alpha releases with full async/await support, although they both still likely have some breaking changes in the pipe so we shouldn't consider using these yet:

https://tokio.rs/blog/2019-08-alphas/

https://seanmonstar.com/post/187493499882/hyper-alpha-supports-asyncawait

Finding a web framework that supports the new versions of each will be the exciting bit, see also #146.

**Comment by bstrie** [comment]
Update: hyper's next stable release looks imminent, likely this week. Once that's out, then we can expect a stable release of tokio-tungstenite, which itself would allow a stable release of warp. Once those three libraries have released, we'll then be able to begin porting to `std::future::Future` (and once that's finished we can then upgrade to async/await, possibly in a separate PR).

**Comment by gakonst** [comment]
Update: hyper 0.13.1 is out, and it's had tokio-0.2 support since 0.13. We're now waiting for tokio-tungstenite which has the corresponding PR almost ready for merge: https://github.com/snapview/tokio-tungstenite/pull/68/files

**Comment by bstrie** [comment]
It occurred to me that we'll probably want to also wait for redis's async/await PR to land, which, according to the maintainers, should proceed during the holidays: https://github.com/mitsuhiko/redis-rs/pull/232

**Comment by gakonst** [comment]
Fixed in https://github.com/interledger-rs/interledger-rs/pull/585
