### ISSUE TITLE
Improve Ethereum Ledger Settlement Engine robustnessss

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#149]
The engine implemented in #125 works but can be improved. In particular:

- [x] When asking for a peer's address, send a challenge which they must sign so that they prove ownership of the key. Otherwise, it's pretty trivial to pretend you are someone else and get the benefit of their settlements https://github.com/emschwartz/interledger-rs/pull/125#discussion_r305142371
 - [x] extend speculative nonces middleware
 - [x] reduce callback hell https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304152825,
 - [x]  return futures and do join_all (or similar) instead of spawning: https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304679388, https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304679066
 - [x] estimate gas and gas price before sending a transaction https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304045049, allow node operator to specify urgency similar to ethgasstation
 - [x] If a transaction is known to have failed, add a a mechanism to persist the amount that account is owed so it could be retried late.
  - [x] Save gas fees by querying the sender's balance before signing a transaction and sending it only if the sender has sufficient balance (ethers.js does that automatically when it calls eth_estimateGas under the hood, need to check if web3-rust does that check) https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304045693
  - [ ] add test: on what happens if the SE dies after making some of the POST requests to the connector but before it saves the current block number? It should be expected to start again and will try to resubmit the same blocks, however it will not submit the same transaction twice, since the check_tx_credited assertion is sufficient to ensure that a transaction is not processed again. https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304676627
  - [ ] optimize calls to connector in case multiple incoming transactions are found from the same account: https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304677692
  - [x] document edge cases: e.g. If the SE goes down for many blocks and then restarts, this will result in a burst of simultaneous requests, which may fail if using Infura or other ETH providers if they're rate limited. https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304706744
 -  [x] Ensure that the `if new_balance > last_observed_balance` check works as intended even when the operator moves their funds to another address when an incoming payment is received (otherwise remove that `if` since it might be a redundant optimization) https://github.com/emschwartz/interledger-rs/pull/125#discussion_r304040412
  - [x] save recently observed block/balance only when all other operations succeed. If any of the tx settlements fails, it will fetch the blocks since the last successful checkpoint and reexecute all the transactions. The check_tx_credited check will ensure that no transaction gets sent twice.
  - [x] Manage incoming ERC20 transfers with event filtering, example: https://github.com/tomusdrw/rust-web3/blob/master/examples/simple_log_filter.rs. 
- [x] Test that `settle_to` works with both sending ETH and an ERC20 token amount

ERC20 Filter guide:
1. Setup filter builder with from/to block https://tomusdrw.github.io/rust-web3/web3/types/struct.FilterBuilder.html
2. Add the filter for `transfer(address,uint256)` where we filter for `address == our_address`
3. For each hit, notify the connector

**Comment by b20160** [comment]
is there a mismatch in the rust implementations? In the es-examples branch, the settlement engine ur is passed as a property 
`{
    "ilp_address": "example.node-a.mike",
    "asset_code": "ABC",
    "asset_scale": 9,
    "max_packet_amount": 1,
    "http_incoming_token": "mike",
    "settlement_engine_url": "http://localhost:8080/rcl"
}`

but when I build and run this branch and create an account with above SE URL it is never hit. Also, all of the endpoints mentioned in the spec are being exposed.

**Comment by gakonst** [comment]
> add test: on what happens if the SE dies after making some of the POST requests to the connector but before it saves the current block number? It should be expected to start again and will try to resubmit the same blocks, however it will not submit the same transaction twice, since the check_tx_credited assertion is sufficient to ensure that a transaction is not processed again. #125 (comment)

Don't think we can make the function call crash during execution.
