### ISSUE TITLE
POST Account .  Empty JSON values for keys

### ISSUE THREAD

**Issue by Neil-Jubinville** [interledger-rs/interledger-rs#166]
I ran into an issue the other day where I was troubleshooting why accounts were not going into Redis. 

I discovered that as I was testing different field values,  I would sometimes just delete my string btp_endpoint : ""  , for example when I was switching to test http peer and I want to zero out that field.  

Sending such a value is not allowed currently (and probably for just some fields)  where server logic tries to parse an address if a key exists.   

I was not expecting the POST Account to crash.  Also the errors in the log were misleading, they did not indicate the key was the issue.    

This one is probably some refactor on error handling.

**Comment by gakonst** [comment]
Closing this as it's stale, if you can reproduce this on master feel free to re-open
