### ISSUE TITLE
Distribute pre-built binaries and/or allow examples to use Docker

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#179]
Compiling the whole project is a relatively slow part of running the examples (as mentioned in https://github.com/emschwartz/interledger-rs/pull/157#issuecomment-515553486). 

To improve the developer experience, we should either distribute pre-built binaries that can be downloaded and used with the examples, or we should make it so the examples can be run in either Docker or "native" mode. The latter option would change the command for running the node from `cargo run...` to `docker run...` based on an environment variable or a flag passed into the script.

**Comment by dora-gt** [comment]
I'm working on this, and the output would be like:
https://github.com/dora-gt/interledger-rs/blob/feature/dx/dockerize-example/examples/simple/README.md

**Comment by gakonst** [comment]
I agree that a docker compose file is a nice way to get a testnet up and running very quickly
