### ISSUE TITLE
Replace numeric account IDs and configured ILP addresses with usernames and dynamically generated addresses

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#186]
- [x] Replace numeric IDs in `interledger-store-redis` / the node with unique ids
- [x] Add usernames to accounts as uid aliases
- [x] Make SPSP payments work with usernames
- [x] Add an auth method to the HTTP API that includes the username (HTTP Basic Auth, separate header, or JWT)
- [x] Remove need for auth tokens to be globally unique
- [x] Remove `ilp_address` from the `Account` (or make it optional, in which case if it is present it would override the automatically generated address)
- [x] Handle ILDCP queries by appending a dot (`.`) and the username to the Node's ILP address
- [x] Merge `IldcpAccount` trait into base `Account` trait and rename `client_address` method to `ilp_address`
- [ ] Don't broadcast node's child accounts if their addresses start with the node's ILP address (if node `example.a` has an account for `example.a.b`, it should broadcast a route to `example.a` but not to `example.a.b`)

Based on https://github.com/emschwartz/interledger-rs/issues/126, https://github.com/emschwartz/interledger-rs/issues/147, and https://github.com/emschwartz/interledger-rs/issues/161

**Comment by kincaidoneil** [comment]
Will clients be able to change their usernames? If so, it might be nice to also have an immutable unique ID for each account to interface with settlement engines (e.g. a UUID).

**Comment by emschwartz** [comment]
Right now I don't see allowing users to change their usernames as a high priority feature, and it's potentially a fairly bad idea to allow. What if you change your username and a friend or customer sends money to your old payment pointer?

**Comment by gakonst** [comment]
Notes from call with Evan:

- unique username, no uuid 
- auth token key in database becomes (username,http_token) so that http_tokens are no longer globally unique 
- multiple authorization methods, 1 with Basic, and 1 with Bearer (`username:token` non-standard format)
- is there anytime a use for an account to have an ILP address that's not part of the node's address space?
- check if we can merge Ildcp account into Account

**Comment by emschwartz** [comment]
> auth token key in database becomes (username,http_token) so that http_tokens are no longer globally unique

Alternatively, it might be better to just index all of the accounts by username and when the auth comes in, look up the account and check the token against what's listed in the account record. Currently we need a separate mapping of token -> accountId but I think we can get rid of that with this change.

**Comment by kincaidoneil** [comment]
> unique username, no uuid

I strongly suggest that each account is identified internally by a unique, not-user-defined ID, and **not** a username (but we should still support usernames):

1. [Using usernames to identify unique accounts seems to be a **highly** discouraged op-sec practice](https://www.b-list.org/weblog/2018/feb/11/usernames/)
   - With unicode, ensuring usernames are unique is actually non-trivial (!)
   - Registration of names "reserved" in other places, e.g. `.well-known`, can cause unexpected problems
2. The more user-provided strings we use within keys, the greater the risk of injection/collision attacks within the DB
   - For example, suppose there's an account `bob`. Then, I create an account `bob:balance`. Suppose account info is stored in `account:<username>`, and balances are stored in `account:<username>:balance`. When I create the second account, does it overwrite the balance of the first account with my account info?
    - Note that poorly implemented settlement engines may also by vulnerable, since they share the same ID space.
    - We can (and should) sanitize user input/escape bad characters before writing keys, and/or can restrict characters usernames can use, etc., but I imagine it's much simpler to limit the attack surface of potential injections in the first place
3. This enables cleanly adding account aliases or supporting username changes, _if_ we decide to add those in the future. Otherwise, the latter would be a nightmare to securely implement; modeling it this way now at least leaves the door open.
   - Note that maybe we'll run into use cases other than users changing usernames, such as operators manually changing usernames.

**Comment by emschwartz** [comment]
Good points @kincaidoneil.

If we use UUIDs to identify accounts internally, the open questions to me would be:
- What goes in your SPSP receiver URL? Your username (`/spsp/bob`) or the ID (`/spsp/f0af1bc4-0427-437b-a0ec-b982d9df7e67`)?
- Similarly, when you query balances or call other HTTP API endpoints, which identifier would it use in the path?
- When setting routes in the routing table (via the API), would accounts be identified by their username or UUID?

**Comment by gakonst** [comment]
Anything that's internal should be done by uuid, anything that involves user interaction such as the SPSP receiver URL should be by username imo.

**Comment by emschwartz** [comment]
After looking through https://github.com/interledger-rs/interledger-rs/pull/233, I'm not convinced the separation between username and account ID makes sense in this context.

I'm leaning toward the option of having a `Username` type that:
1. Normalizes string input using NFC unicode normalization (using [this function](https://docs.rs/unicode-normalization/0.1.8/unicode_normalization/trait.UnicodeNormalization.html#tymethod.nfc))
2. Validates that the string matches the regex `/^\w{1,32}$/u` (the unicode flag is set)
3. Converts the string to lowercase

I think this would address the issues in the article @kincaidoneil linked.

Here are the places we need account identifiers:
- Authentication (login identifier)
- URLs for SPSP endpoints, balances, etc (public identifier)
- Store methods (system-level identifier)
- DB index of accounts (system-level identifier)
- Communication with the settlement engine (system-level identifier)

The other options are:
- Random account ID - this requires an extra call to the DB or cache to look up the ID based on the username and doesn't solve the issue with intentionally confusing usernames in URLs (I could be convinced this is fine if this is what massive web services already do)
- Deterministic account ID - this doesn't solve the issue with usernames in URLs and wouldn't allow users to change their usernames without changing the account ID

Note that account aliases would be easy to add no matter what we choose.

**Comment by kincaidoneil** [comment]
> I'm not convinced the separation between username and account ID makes sense in this context

Why? What's that different about this use case from most web services?

> this requires an extra call to the DB or cache to look up the ID based on the username

Can't this be batched when the request is authenticated in a single DB call?

**Comment by emschwartz** [comment]
> Can't this be batched when the request is authenticated in a single DB call?

Which requests are you talking about batching? If you "batch" the following two requests: 1) get the ID from the username and 2) make the other call to the store with the ID, what's the difference between that and just making the store methods take the username?

**Comment by emschwartz** [comment]
@kincaidoneil made a good point that most -- if not all -- of the times there would be an extra DB call to look up the account ID from the username would be on infrequent admin API calls, rather than every time a packet is being processed.

Therefore, I'll go back to agreeing that we should use account IDs in most of the `store` methods, as well as internally in the DB, and have a separate call for looking up the account ID by the username. This will be used whenever the username appears in the URL path, as with `/spsp/:username` and `/accounts/:username/balance` calls.

That said, I think we still want to have the `Username` struct and associated validation described above.

**Comment by gakonst** [comment]
> Remove ilp_address from the Account (or make it optional, in which case if it is present it would override the automatically generated address)
> Handle ILDCP queries by appending a dot (.) and the username to the Node's ILP address

From a short discussion with Evan, it's not clear to me why the above 2 are useful, since it seems that most times a user will be overriding their address.

```
I think this example shows that you override the username with a custom ilp address always unless you are inserting an account with a CHILD relation to your node:

Username: Alice / Node ILP Address: example.alice
Username: Bob / Node ILP Address: example.bob
Username: Charlie / Node ILP Address: example.charlie

Alice inserts her account to her node. The address would become
example.alice.Alice. She doesn't want alice to display twice, so she overrides
with `example.alice`.

Alice inserts Bob to her node, with a peer relationship. If Bob's username were
to be appended to alice's node address, then Bob's address would become
`example.alice.bob`. This is undesirable, as they are peers on the same address
hierarchy. She inserts Bob's account and overrides the address to `example.bob`.

Bob inserts Alice as a peer, so he overrides her address with `example.alice`,
to avoid replying to ILDCP requests with `example.bob.alice`.

Bob inserts charlie as a CHILD, without address. As a result, Charlie's address
via ildcp through Bob's node is `example.bob.charlie`.

Charlie inserts his account to his node, and overrides, similar to Alice. He
inserts Bob's account as a PARENT, with `example.bob` as override address. 

Am i missing something about the intended behavior?                        
```

> It might make sense to separate out the use cases for getting the account's ILP address, rather than thinking about what the ILP address of each account should be.
> It's strange if a parent or peer sends you and ILDCP query anyway, so it's fine if you responding with `example.child.parent` -- since if you really wanted to send a packet to the parent's account on the child node, that would be the way to address it.
> STREAM/SPSP is similar to ILDCP.
> For routing decisions, you don't need to have the peer or parent node's ILP address configured because they'll broadcast the routes to you. When you look in the routing table, you'll find the parent and peer addresses (as reported by them, rather than as configured by you) and route the packets to the correct account

---

> Merge IldcpAccount trait into base Account trait and rename client_address method to ilp_address

Now that the `Account` trait also has a `username` method, I feel that this separation between the two is nice to have, hence I'd say we skip merging them. 

> Don't broadcast node's child accounts if their addresses start with the node's ILP address (if node example.a has an account for example.a.b, it should broadcast a route to example.a but not to example.a.b)

It seems to me that this should be handled separately as it's a ccp level optimization?

**Comment by gakonst** [comment]
Should this be closed in favor of #248?

**Comment by gakonst** [comment]
> Most accounts will be child accounts (assuming you have far fewer peers and upstream providers), so it's worth removing the need to configure an ILP address for those.

OK then we should probably add a BTP end to end test which creates a big hierarchy to test this functionality. It'd be nice if we had a tool where we can feed it a network topology and it generated all other account information randomly and ran a simulation for btp/http/engine peering.

**Comment by emschwartz** [comment]
I don't think we need a big hierarchy to test this -- one level should be enough, no?

**Comment by gakonst** [comment]
>  Don't broadcast node's child accounts if their addresses start with the node's ILP address (if node example.a has an account for example.a.b, it should broadcast a route to example.a but not to example.a.b)

I think here you mean that we should broadcast only to our immediate children, instead of children of our children and so on?

**Comment by emschwartz** [comment]
> I think here you mean that we should broadcast only to our immediate children, instead of children of our children and so on?

@gakonst no, that isn't what I meant. It should broadcast routes to any accounts that have `send_routes: true`. The question is which of its routes it should send. The point of this bullet was to say that if my address is `example.evan`, I will not send you routes like `example.evan.account1`, `example.evan.account2`, etc. Instead, I will filter out those sub-accounts (anything that starts with my address) from my route broadcasts.
