### ISSUE TITLE
Reconnect database if connection drops

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#193]

**Comment by emschwartz** [comment]
This was partially done by https://github.com/interledger-rs/interledger-rs/pull/365.

The only thing that's missing is to allow `redis::Script#invoke_async` to be called on a generic `redis::aio::ConnectionLike` instead of `SharedConnection` so we can pass the wrapped `SharedConnection` to it.

**Comment by emschwartz** [comment]
Waiting for https://github.com/mitsuhiko/redis-rs/pull/242 to be merged before this can be finished

**Comment by gakonst** [comment]
@emschwartz https://github.com/mitsuhiko/redis-rs/releases/tag/0.13.0 release is in
