### ISSUE TITLE
Make settlement-engine to take environmental values

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#194]
While `node` takes environmental values, `ethereum-ledger` does not.
It might be better to take environmental values to have consistency.

**Comment by dora-gt** [comment]
If @gakonst doesn't mind, I'd like to fix this just for my Rust study.

**Comment by gakonst** [comment]
Sure.

**Comment by dora-gt** [comment]
It seems that this issue is related to #169, #171, #206. These should probably be solved at the same time.

**Comment by emschwartz** [comment]
Closed by https://github.com/interledger-rs/interledger-rs/pull/290
