### ISSUE TITLE
Allow env vars to override config file values

### ISSUE THREAD

**Issue by inthecloud247** [interledger-rs/interledger-rs#206]
Right now, I can set config values either by using the config file, or via env vars. For example:

```
ilp_address: "test.mynode.node1"
```

is equivalent to:

```
export ilp_ilp_address="test.mynode.node1"
```

However, when I set both values I get an error:

```
thread 'main' panicked at 'Must provide config file name or config environment variables: duplicate field `ilp_address`', src/libcore/result.rs:999:5
```

The expected behavior (imo) would be that env var values should override config file values. This would allow us to set sane default values in a config file, while also allowing new values to be set via env vars at runtime.

**Comment by emschwartz** [comment]
There may be a very simple fix to this, but if not it may be worth fixing this when we switch config parsing libraries (see https://github.com/emschwartz/interledger-rs/issues/171)

**Comment by emschwartz** [comment]
Closed by https://github.com/interledger-rs/interledger-rs/pull/290
