### ISSUE TITLE
STREAM receiver should only try to parse packets for addresses starting with its prefix

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#209]
Right now the STREAM server checks every incoming packet to see if it can regenerate the correct shared secret from the nonce in the ILP address.

The server should be configured with an ILP address and only check packets whose destination addresses start with its address.

This would probably be good to do after https://github.com/emschwartz/interledger-rs/issues/186, because then every account's ILP address will be derived from the node's address.

**Comment by dora-gt** [comment]
Maybe not yet? pending till we can differentiate the final destination from local account (am I understanding right?)

**Comment by matdehaast** [comment]
@emschwartz is the idea that the stream receiver would have its own `sub-address` of the connectors address. ie if the connector has an address `test.connector`, the receiver would only check packets addressed to `test.connector.stream`?

The above is how we are handling it, but one thought was is there a concern that the address for incoming stream packets is known? At face value I don't think so but was wondering if there is something I had not considered

**Comment by emschwartz** [comment]
Actually I meant that it should check whether the address at least starts with `test.connector` in your example (before it was just trying every packet that went through). Adding another segment could be a further optimization to avoid it trying a decrypt operation on other packets, but decrypting is really fast because of hardware optimizations so I'm not sure how important that is to implement now.

The only real downside of including a segment called `stream` in plaintext is that some other systems may come to expect such a segment. The experience of the people working on QUIC suggests that everything that can be encrypted should be to avoid ossification (see [here](https://www.ietfjournal.org/quic-bringing-flexibility-to-the-internet/)). You could also have the STREAM server generate segment from an HMAC of its server secret and some magic bytes so that it's unique to that server but wouldn't be quite as easy to identify and build for on the network level.

**Comment by emschwartz** [comment]
Yup, good point
