### ISSUE TITLE
Remove Interledger Store Memory

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#216]
Currently it's only used in the CLI, where I'd expect that we would pass a redis instance instead. Do we need it or can we remove it?

**Comment by emschwartz** [comment]
The CLI functions aside from the `node` are completely stateless so it wouldn't make sense to require Redis for them.

That said, we _may_ want to remove those functions and just point people to use the node. In the future we could add a different type of CLI that makes HTTP calls to the `node`.

**Comment by emschwartz** [comment]
> That said, we _may_ want to remove those functions and just point people to use the node. In the future we could add a different type of CLI that makes HTTP calls to the `node`.

https://github.com/interledger-rs/interledger-rs/issues/228

**Comment by gakonst** [comment]
OK so once #228 is in, we should remove the in-memory store along with `cli.rs` related functionality.

**Comment by bstrie** [comment]
Closed by #321.
