### ISSUE TITLE
Allow users to modify certain account settings?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#229]
Right now, most of the HTTP API endpoints are admin-only. Should we allow users to modify certain settings on their account?

Some fields we may want to make modifiable:
- User password / API key?
- Username?
- Settlement details (came up in https://github.com/interledger-rs/interledger-rs/issues/121)
- HTTP or BTP connection details

Obviously fields like balances and limits must not be modifiable.

**Comment by gakonst** [comment]
We'd add an extra API call that to check the auth token, load the account, modify the account based on provided information and then call update? 

https://github.com/interledger-rs/interledger-rs/blob/gakonst-auth-per-account/crates/interledger-api/src/lib.rs#L61-L86
```
pub struct AccountDetails {
    pub ilp_address: Address, 
    pub username: String, // YES
    pub asset_code: String,
    pub asset_scale: u8, 
    #[serde(default = "u64::max_value")]
    pub max_packet_amount: u64,
    pub min_balance: Option<i64>,
    pub http_endpoint: Option<String>,
    pub http_incoming_token: Option<String>,
    pub http_outgoing_token: Option<String>,
    pub btp_uri: Option<String>, // YES
    pub btp_incoming_token: Option<String>, // YES 
    pub settle_threshold: Option<i64>, // YES
    pub settle_to: Option<i64>, // YES
    #[serde(default)]
    pub send_routes: bool,
    #[serde(default)]
    pub receive_routes: bool,
    pub routing_relation: Option<String>,
    pub round_trip_time: Option<u32>,
    pub amount_per_minute_limit: Option<u64>,
    pub packets_per_minute_limit: Option<u32>,
    pub settlement_engine_url: Option<String>,
}
```

**Comment by emschwartz** [comment]
What would the relationship be between the two structs? Would one be inside the other or would they be separate?

I agree with the config options you listed as user-modifiable.

**Comment by kincaidoneil** [comment]
> settle_threshold and settle_to definitely must be possible to be changed by the user

Why? And couldn't I maliciously configure the `settle_to` so you immediately start prefunding me?

**Comment by emschwartz** [comment]
> Why? And couldn't I maliciously configure the settle_to so you immediately start prefunding me?
Just make it so it can't go negative. Allowing the user to specify the `settle_threshold` seems more useful than the `settle_to`, because that would allow them to opt for more or less frequent settlement, depending on their level of trust with the node and the cost of the settlement.
