### ISSUE TITLE
Auto-publish artifacts when new versions are tagged

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#230]
We should start tagging versions of the components of this project. This includes:
- Docker image
- `interledger` crate
- `interledger-*` crates

It seems like the version tags on the repo should line up with the Docker image and the `interledger` crate.

I would propose that we version the sub-crates separately and let their versions be whatever they may be.

Thoughts? @gakonst @dora-gt @bstrie

**Comment by dora-gt** [comment]
I understand the version policy. Here, we should consider:

1. The versioning policy
    - Bump up the ONLY `ilp-node` crate; the other crates are not affected.
1. The release policy
    - Should we follow the Rust's release policy?
        - `Nightly` builds
        - `Beta` releases
        - `Stable` releases
1. The artifacts
    - Binaries
        - Should we provide binaries? for what platforms? how?
    - Docker Images
        - We should properly tag the image versions. I don't think this is a big issue. Just using the `ilp-node`'s crate version would be appropriate.
    - Documents
        - We should NOT use `nightly` builds for documents because it might cause errors. We should use `stable` (or at least `beta`) releases for documents.

So the questions are:
1. Should we follow the Rust's release policy (and its branching model)?
1. How, for what platform, should we provide binaries?
    - GitHub's assets
    - interledger.rs site

What do you think? @interledger-rs/contributors

**Comment by dora-gt** [comment]
My thoughts.

1. Should we follow the Rust's release policy (and its branching model)?

Maybe YES, we could also adopt some other strategies like [A successful Git branching model](https://nvie.com/posts/a-successful-git-branching-model/) but it seems that both work (IMO) and we live in the Rust world, it seems natural to adopt Rust's releasing model if there isn't any problem.

JFYI: the main difference AFAIK between "A successful Git branching model" and Rust's one is that "A successful Git branching model" expects that the master is always `stable`. The commits should be tested and should have worked a while. In the Rust's model, it seems that the `master` branch is `unstable` and being continuously tested.

2. How, for what platforms, should we provide binaries?

My answer is:

- What platforms
    - Linux based OSs (`musl`)
    - macOS
- How
    - GitHub assets.
    - Additionally, package managers could be considered. e.g. `brew`
    - If we had the `interledger-rs` website(#378), that would be another option.

I think we should focus on what is really needed or used. I considered:

- Most developers seem to be using Linux based OS. Then providing `musl` binaries would suffice.
    - I'm not sure how many people want binaries for Unix based systems other than macOS.
- Some developers might be using `macOS`. Then providing binaries on `brew` would be the easiest way.
- I'm not sure how many people want to use `ilp-node` on Windows. It might not worth providing binaries.

**Comment by emschwartz** [comment]
:+1: to the idea of providing binaries for linux + mac using github assets and potentially other package managers. We should also tag docker images (https://github.com/interledger-rs/interledger-rs/issues/427) at the same time

I would recommend splitting this up into a number of PRs.

Also, if we publish binaries, could/should we get rid of the docker-based instructions for the examples? You've needed to put a lot of infrastructure in place in the markdown files and CI to support running it either way. If users don't need to build the whole project themselves, it might be enough to tell them to download the available binaries.

Side note, we should not prioritize this but I would love to distribute the `interledger-rs` node using https://wapm.io/

**Comment by dora-gt** [comment]
If the main reason for using Docker images is that they are faster because they don't need to be compiled, I think we don't need to provide the docker mode for examples, once binaries are provided. The markdowns and the CI process will be simplified.

I would like to prioritize the tasks.

1. Tag docker images with versions (tags)
    - Assuming every version is tagged, using the tag would suffice though I'm not sure how to kick a CircleCI job only if a tag is added. I'll look into.
1. Build and publish binaries to a single package repo (whatever is the easiest one)
    - GitHub Assets using [the API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) because it could be used for any platforms.
    - We have to make sure that the tags are pushed to GitHub correctly when `cargo release` because the assets will be attached to the tags.
1. Fix examples to use binaries, and remove Docker mode, simplify CI
1. Publish new versions on crates.io when a git tag is added (potentially)
    - You (Evan) 'll need to register an API token of `crates.io` to CircleCI, in order to publish crates automatically. It seems that also `cargo release` could publish automatically. Do we have any reason not to use `cargo release`?
1. Maybe publish the binaries to other package repos
1. WebAssembly?

If you have opinions on this order, please tell me.

**Comment by emschwartz** [comment]
Sounds good. I think it's working on 1-4 now and leaving 5-6 until some time later.

> It seems that also cargo release could publish automatically. Do we have any reason not to use cargo release?

I've been running `cargo release` manually on my computer to publish the packages until now. I don't think it's perfect but it is better than running the process ourselves. The main issue I have with it is that it publishes a new version for the crates even if nothing has changed since the last one.

**Comment by dora-gt** [comment]
> I think it's working on 1-4 now and leaving 5-6 until some time later.
OK.

I was assuming that we would use `cargo release` manually to bump versions and push its git tags. Do you mean we should not use `cargo release` at all?

My image was like:
- Bump versions + git tags with `cargo release`
- Push the git tags and CI is kicked.
- Publish crates on CI process using `cargo publish`
    - Only if something is changed? (maybe need to do something)

**Comment by emschwartz** [comment]
I mostly agree with that. Let's get it set up so that Circle will run `cargo publish` if the version of a given crate is not the same as the one available on crates.io. Then, we can either use `cargo release` to bump the versions or we can switch to doing it manually.

**Comment by dora-gt** [comment]
No problem. Let's do step by step and check if it works well.

**Comment by dora-gt** [comment]
Progress: https://github.com/interledger-rs/interledger-rs/pull/466

**Comment by emschwartz** [comment]
Can this be closed?

**Comment by dora-gt** [comment]
Yes, I'll close.
