### ISSUE TITLE
Check APIs and Docs are up-to-date

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#239]
The following 3 might not be consistent:

- The current implementation
- [Candidate RFC](https://github.com/interledger/rfcs/pull/536)
- `docs/api.md`

We might need to check and correct.

https://interledger.slack.com/archives/CHC51E54J/p1566498083177700

**Comment by dora-gt** [comment]
It might be better to generate API docs from the source codes though I haven't checked it is possible or not.

**Comment by emschwartz** [comment]
The HTTP API doc is definitely out of date because it has not been updated to use `username` instead of `id`

**Comment by dora-gt** [comment]
Things I noticed around the settlement RFC and the implementation are:

- `settlement-engines` does not implement `delete` for accounts, which is defined in the [RFC](https://github.com/interledger/rfcs/blob/master/0038-settlement-engines/0038-settlement-engines.md).
- `send_money`, `receive_message`, `do_receive_settlement` and `do_send_outgoing_message` should return `201` according to the RFC, but it seems that it returns `200`.
    - Also I feel a bit strange that `ethereum-ledger` returns HTTP Status codes. They should not know about HTTP. They just do settlements. That's the responsibility of API endpoints IMO.
- Shouldn't we define `incoming message`s more in detail?
    - If I were an implementor of a settlement engine, I might feel curious about the detail. How should I use it? or What is the typical implementations?

**Comment by dora-gt** [comment]
API docs will be updated by #444

**Comment by emschwartz** [comment]
> Shouldn't we define incoming messages more in detail? 

This should go in the docs for implementing a settlement engine, rather than the API docs

**Comment by emschwartz** [comment]
@dora-gt can this be closed now?

**Comment by dora-gt** [comment]
Yes, API doc is up-to-date now and other issues are reported.
