### ISSUE TITLE
Get node ILP Address from parent

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#248]
Right now the `node` needs to be configured with an ILP address. If you are running a node as a "child" of another, it would be easier and more reliable to automatically query the parent node for the ILP address. (This would also mean that with https://github.com/interledger-rs/interledger-rs/issues/186, the ILP address of each account on the node will be correct without any configuration, whereas right now you can mess it up by using an un-routable address)

- [ ] Make `ilp_address` optional in the `node` configuration
- [ ] If `ilp_address` is not provided, make an ILDCP query to get the address
- [ ] Figure out which account to send the ILDCP query to (Should there be an index of accounts listed as `Parent`s? If there are multiple, which one should we use?)
- [ ] What happens when the node is run with no accounts configured? Should there be a hook on the account creation API that would recognize when a "parent" is added that would send the ILDCP query and update the node's address?

**Comment by gakonst** [comment]
From the ILDCP Spec:

> if the node has a parent in the network hierarchy, the ILP address of the child node can be allocated to it by the parent. This is done using ILDCP.

Based on that and your comment:
>  Figure out which account to send the ILDCP query to (Should there be an index of accounts listed as Parents? If there are multiple, which one should we use?)

This makes me believe that it only makes sense for a node to ever have 1 parent. Is that the case, @emschwartz?

```
a.a --- a.b --- a.c <- peers
 \       |      /     ^ child v parent
   ----- a -----
         | <- peers
   ----- b -----
  /      |      \
b.a --- b.b --- b.c <- peers
                / \
```

**Comment by sappenin** [comment]
> This makes me believe that it only makes sense for a node to ever have 1 parent. Is that the case, 

My understanding is that a node _could_ have multiple parents (though I would be open to restricting that) as long as it only performs IL-DCP with one of them. 

In Java I just choose the first account that is a parent, but we should probably have a smarter way to indicate which parent to use? Or else maybe restrict the number of parent nodes?

**Comment by sappenin** [comment]
> Can it ever be the case that an account is inserted to a node as Child, and we'd want to set receive_routes = true?

I would say, "no" because one of the primary purposes of the "child" classification is to indicate that the parent node doesn't really trust the routing tables of that child peer. If a parent node _does_ trust a child, it should classify that account as a `peer` instead.

> I would expect that anytime a Child node tries to broadcast its routes to us, we should reject them. Similarly, whenever we set a node as a Parent, we should definitely receive routes from them.

That's my understanding. [JS](https://github.com/interledgerjs/ilp-connector/blob/master/src/services/route-broadcaster.ts#L130) and [Java](https://github.com/sappenin/java-ilpv4-connector/blob/master/connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultRouteBroadcaster.java#L163) implementations do this -- although in fairness, Java is a copy of JS, and just because JS did it doesn't mean it's correct.

**Comment by sappenin** [comment]
> Does this mean we can remove receive_routes and send_routes and from CcpRoutingAccount and just use the routing_relation to judge if we should drop broadcast packets or not [1] [2]? I guess their main use is when 2 nodes are connected together with a Peer relationship, but wouldn't they both be true in that case?

Curious to hear more opinions here, especially from @emschwartz. I suppose it could be the case that there is some other reason to accept routing updates from a child peer?

**Comment by emschwartz** [comment]
I opened separate issues to discuss the questions @gakonst brought up.

> Could we remove the spawn_tasks variable and use cfg(test) in code-blocks like this? As per the comment in spawn_tasks' definition, this seems to be a variable related to tests.

Sounds reasonable to me.
