### ISSUE TITLE
Improve HTTP responses

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#250]
Currently HTTP endpoints return JSON like:

```
{"type":"about:blank","title":"Internal Server Error"}
or
{"type":"about:blank","title":"Bad Request"}
```

This tells nothing for developers and it's hard to assume what's the problem. We need to improve this.

https://interledger.slack.com/archives/CHC51E54J/p1566983918002000

**Comment by emschwartz** [comment]
It looks like we can use https://github.com/dtolnay/path-to-error along with the error message returned by `serde_json` to provide a more helpful error message

**Comment by dora-gt** [comment]
Because the testnet document depends on `test.xpring.tech`, I'll try to improve this in parallel.

**Comment by dora-gt** [comment]
memo: https://github.com/carllerche/tower-web/issues/28#issuecomment-450699502

**Comment by dora-gt** [comment]
It seems that improving `tower-web` itself is more appropriate:

https://github.com/carllerche/tower-web/blob/master/src/extract/serde.rs#L179-L181

though we might be able to implement our own `extract` trait (I'm not sure). If we implement on our own, it might be more flexible.

If you @interledger-rs/contributors  have any opinion, please tell me.

**Comment by emschwartz** [comment]
I'm in the process of switching everything over to `warp` (away from `tower-web`) so I wouldn't focus on implementing this for `tower-web`.

`warp` gives you a bit more manual control over error handling so it shouldn't be too difficult to implement once we decide what we want. See how "rejections" are handled [here](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-api/src/lib.rs#L184-L193). We can change our own `ApiError` type to include more details of the error and then change that error handling logic to include more details in the HTTP response body.

**Comment by dora-gt** [comment]
Ahhh! sorry, I forgot. Yes, we should use `warp`. Thank you. I'll check the code.

**Comment by gakonst** [comment]
Closing, our error handling is very nice now
