### ISSUE TITLE
Decide how nodes will connect to the testnet

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#260]
2 options:
1. support BTP account creation (implement BTP open signup for the Redis store and include that in the node) 
2. pre-load accounts on the testnet nodes

The second is simpler, I think that BTP is mostly understood by @emschwartz only hence could maybe be a lower priority issue

**Comment by emschwartz** [comment]
Actually the options are:
- BTP account creation
- Expose `POST /accounts` on testnet nodes to allow new nodes to add themselves (with any parameters)
- Create a separate signup endpoint that allows new nodes to connect and only set specific parameters (for example, it would not allow them to set the `min_balance`)
- Create a website where users could sign up to get testnet credentials, which would call a separate backend service that would insert the new account using `POST /accounts`
- Pre-load accounts into the testnet nodes and give out the credentials for the hackathon (only a temporary solution)

**Comment by emschwartz** [comment]
I think we should go with:
> Create a website where users could sign up to get testnet credentials, which would call a separate backend service that would insert the new account using POST /accounts

This is the one that's most likely to work for the live net and it's pretty simple to go to a website, click "Generate Credentials", and then plug those into your node. It also has the advantage of providing you credentials that you can use to interact with the HTTP API in addition to using BTP and ILP-over-HTTP to send ILP packets. Finally, not trying to create a standard signup API avoids a bunch of bikeshedding over what that should look like and what options are supported.

**Comment by emschwartz** [comment]
For now, we've decided to implement the website "generate credentials" option.

@kincaidoneil had an idea for an OAuth-based signup that we may want to use later but we can document that in another issue.
