### ISSUE TITLE
Have multiple Settlement Engines supported on the testnet

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#264]
As title

**Comment by kincaidoneil** [comment]
#### Settlement engines for Hackathon Kit:

- [x] XRP on-ledger (*pending updates)
- [ ] XRP paychan
- [x] ETH on-ledger
- [ ] Lightning

**Comment by gakonst** [comment]
> LN

This would assume the user is running a `lnd` node or similar?

**Comment by kincaidoneil** [comment]
> This would assume the user is running a lnd node or similar?

For now, yes. Ultimately I'd like the SE to bundle an LND node using Neutrino or something so that's not necessary
