### ISSUE TITLE
Question: CongestionController logic for Reject calls with F08 Packet lacking details

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#266]
**Question**: What should the `max_packet_amount` adjustment logic look like when the  [CongestionController processes a reject packet](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-stream/src/congestion.rs#L142) with an F08 error code but not attached details?

This issue is related to #49 (maybe just a dup), but #49 really centered around the connector not returning an F08 rejection code at all, whereas this question centers around what the Controller should do when an F08 packet is encountered, _but_ is lacking the details data).

In this case, since we have no information from the Connector around what a desirable max packet should be, should we just cut the `max_packet_amount` in half and try again?

**Comment by emschwartz** [comment]
> should we just cut the max_packet_amount in half and try again

yes

Closing this because it is the same issue described in #49
