### ISSUE TITLE
Should a node's ILP address automatically be updated if the Parent's ILP address changes?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#279]
If a `Parent` node changes their address, the `Child` nodes would need to update their addresses in order to continue receiving packets. In order to support this, we would either need the `Child` nodes to routinely re-send ILDCP requests (or pings) to see if their address changed or we would need a push-based mode of ILDCP that would allow the `Parent` to notify the `Child` when the address changes. Is it worth supporting this?

I think this question comes down to whether we expect `Parent` nodes to change their addresses on a similar time scale to the duration of a `Child` account connection. This won't be an issue if the `Child` connection is very short lived, for example in the case of an application connecting and making a couple of payments, because it will make an ILDCP request when it connects. In contrast, if you have three long-running nodes arranged hierarchically (A -> B -> C, where the arrows indicate a Parent to Child relationship), it would be an issue for C if B's address changes. If A and B are both large providers, however, you would probably expect them to have static ILP addresses rather than having B query for its address dynamically.

It's interesting to note that the Internet doesn't really need to deal with this because of NAT traversal. My computer doesn't care if my router's IP address changes, because my computer only has a local IP address anyway.

FWIW, I don't think it's worth worrying about this case now, because it's likely that proper providers will have static ILP addresses and I don't really see a use case for multiple hierarchically connected nodes with dynamic ILP addresses.

This originally came up in https://github.com/interledger-rs/interledger-rs/issues/248#issuecomment-527849627.

**Comment by gakonst** [comment]
We'll add an in-memory loaded address in the store which defaults to "local.host" or similar. When a parent is added via API, the API makes a call to the parent's ILDCP and updates node's address to the response.

All services that need to use the node's address, will take an instance of the store and load the address from there.

We assume that there will not be a need for dynamic reconfiguration of the network in case a parent node in the network changes their address.
