### ISSUE TITLE
Support having multiple "Parent" accounts?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#280]
The Routing Relation concept and ILDCP were both heavily inspired by the internet, which was not really built to support multiple upstream internet connections. Should we assume that each node will only have a single upstream provider or should we support having multiple?

Reasons to support multiple upstream providers:
- Comparing rates from different connectors, potentially in real-time
- Connecting your node to multiple remote accounts denominated in different currencies
- Redundancy in case one provider is temporarily unavailable
- Using Interledger for exchange, as for a use case like [Switch](https://github.com/kava-labs/switch), in which you would want to send and receive through different accounts, potentially on different connectors
- ILP is different from the Internet and it's a lot more likely that you have multiple financial accounts than having multiple internet providers (although with WiFi + cellular data we do have plenty of times now where devices may have multiple IP addresses)

This affects:
- Which node(s) to send an ILDCP request (https://github.com/interledger-rs/interledger-rs/issues/248)
- Which address we use as the base for the addresses we assign to `Child` accounts
- What address to include in an SPSP response and, thus, which address other nodes should send STREAM packets to (also, [Should SPSP support returning multiple ILP addresses?](https://forum.interledger.org/t/should-spsp-support-returning-multiple-ilp-addresses/756))

Supporting multiple `Parent`s, and potentially multiple ILP addresses per account, is a lot more complicated than only allowing one. However, a number of people have been frustrated in the past by [`moneyd`](https://github.com/interledgerjs/moneyd)'s inability to support having multiple accounts in different currencies so it may be worth working on.

This originally came up in https://github.com/interledger-rs/interledger-rs/issues/248#issuecomment-527849627.

**Comment by gakonst** [comment]
As discussed, we'll stick with only 1 parent for an MVP.

**Comment by gakonst** [comment]
Closing, multiple parent accounts is a bad idea for sure
