### ISSUE TITLE
Connect to BTP server when account is added with a btp_uri field

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#285]
See TODO [here](https://github.com/interledger-rs/interledger-rs/blob/a7088a41c5a38c3ba8acf34712e6a9e680905be6/crates/interledger-api/src/routes/accounts.rs#L84-L85)

**Comment by emschwartz** [comment]
We should probably also connect if an account is updated and has a `btp_uri` set

**Comment by gakonst** [comment]
Probably doable as part of #248 #276
