### ISSUE TITLE
Should we make the API field names more consistent with the node configuration?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#286]
We are making a number of breaking changes in https://github.com/interledger-rs/interledger-rs/pull/236 to make the naming of config parameters more consistent. Is it worth making a bunch of breaking changes to the API to make the field names more consistent as well? For example, `http_endpoint` could be `http_server_url` and `btp_uri` could be `btp_server_url`

**Comment by gakonst** [comment]
I'm fine with that. Let's also use that PR as a chance to split out the btp_uri into `btp_outgoing_token` and `btp_server_url` (to avoid having to prefix the URI with credentials)

**Comment by bstrie** [comment]
I'd say it's now or never. 👍
