### ISSUE TITLE
Stream Crypto: Stop re-arranging AuthTag in CipherText

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#310]
In [crypto.rs](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-stream/src/crypto.rs#L92) the AuthTag is moved to the beginning of the ciphertext because this is how the Javascript implementation works.

However, the Rust [ring](https://briansmith.org/rustdoc/ring/aead/index.html) library and Java's implementation of AES-GCM arrange the AuthTag/Ciphertext in the same manner (i.e., opposite of whatever the [JS implementation is doing](https://github.com/interledgerjs/ilp-protocol-stream/blob/master/src/crypto.ts#L67)).

Currently, both Rust and Java implementation adjust for this to accommodate JS, _however_, I suggest we invert this and allow Rust and Java to arrange ciphertext bytes in their "normal" ordering, and maybe even update the JS lib to reverse itself. This will yield two things:

1. It means that we don't have to re-arrange bytes on _every_ STREAM encryption/decryption operation for all time (twice per frame, one at the sender to encrypt and one at the receiver to decrypt), which probably will have _some_ performance impact.

1. It means that new implementations of STREAM that might come along in the wild won't have to do this goofy byte arrangement (assuming that Rust and Java libraries are adhering to some sort of _normal_ byte arrangement...).

_Note: See https://github.com/hyperledger/quilt/issues/237 for tracking in ILP Java._

**Comment by sappenin** [comment]
One thing we could do here is to release a version `1.0`or whatever of our STREAM libraries that works "as-is", and then fix this is a future release (e.g., `v1.1`). Though depending on how many "in the wild" JS implementations are out there, this change might be difficult to pull off. 

Another alternative is to attempt to open a STREAM with the "correct" ordering, and failing that, try to open a STREAM with the inverted byte-ordering on the off chance that the receiver is a JS receiver or an older version of Rust/Java.

Open to other ideas here as well.

**Comment by emschwartz** [comment]
This would be a breaking change to the STREAM spec so I don't think it's a good idea to switch it now, even though I now regret the ordering I chose.

**Comment by sappenin** [comment]
hmm....my hesitation is that this ordering appears to be normative (or at least implied-normative) per `5.2.1.2 Output Data` of https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf. That plus the fact that major libraries across languages use this ordering gives me pause -- especially since we don't have a lot of software in the wild just yet.

I think we could introduce the change in a non-breaking manner, meaning: update the Spec, and then update implementations to support both modes (i.e., see fallback comment above) so that stuff doesn't actually break in the wild -- and eventually JS, Java, and Rust become spec compliant (but it doesn't have to occur all at once).

**Comment by tarcieri** [comment]
I would agree the AES-GCM tag belongs at the end of the ciphertext message.

Generally this is the case for every standardized AEAD mode (the only exception I can think of is RFC 5297 AES-SIV, however RFC 8452 AES-GCM-SIV switched to the same convention of using a tag at the end), so I'd consider it "weird" to prepend the tag, not just for AES-GCM, but for AEADs in general.

**Comment by sentientwaffle** [comment]
> It means that we don't have to re-arrange bytes on every STREAM encryption/decryption operation for all time (twice per frame, one at the sender to encrypt and one at the receiver to decrypt), which probably will have some performance impact.

AuthTag-as-suffix is only more performant for decryption (with no difference for encryption). During encryption the ciphertext and tag are cloned regardless when the nonce is prepended. It is simpler to implement, which is great -- but I'm not sure that it warrants a breaking protocol change on its own. Any gradual change would be more complex than what we have now.

https://github.com/hyperledger/quilt/issues/237#issuecomment-534826071:
> That said, implementations of STREAM can support both modes (e.g., pick one mode, and failing that, try the other) when doing AES-GCM encryption/decryption. That way, software doesn't have to upgrade in order to work with "fixed" implementations. But in the long run, all implementations should be fixed in order to accommodate the "typical" style of doing this type of encryption.

I don't see how that would work. Implementations need to know in advance whether the remote supports tag-at-suffix when encrypting a packet.

---

imo: create a "STREAM v2 wishlist" issue in the interledger/rfcs repo. When there are eventually enough breaking changes to justify a backwards-incompatible release, implement them together and bump the protocol (and packet) `version`.
