### ISSUE TITLE
Default route

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#332]
Nodes should be able to configure a "default route" so that even if they do not have a specific route to a destination, they will try forwarding the packet to the default route's next hop. For child nodes, this should automatically be set to the parent. For others, we may want to allow this to be configured separately.

**Comment by gakonst** [comment]
note: A node cannot know that it's a child currently

**Comment by emschwartz** [comment]
It would just check if it has a parent
