### ISSUE TITLE
Push bundled interledgerrs + redis docker image to dockerhub

### ISSUE THREAD

**Issue by nhartner** [interledger-rs/interledger-rs#333]
I would like the bundled interledger+redis image pushed to dockerhub as part of the build. I’ve found it useful for running integration tests as part of our Hyperledger/Quilt java build so I can spin up a fully functioning all-in-one Rust Interledger Node w/ embedded Redis. I’ve been building and pushing this myself manually to dockerhub but not a good long-term solution.

**Comment by matdehaast** [comment]
@dora-gt I would recommend looking at removing the `.sh` script as the entry point and use something like [supervisord](http://supervisord.org/) for managing multiple processes within a single docker image.

**Comment by dora-gt** [comment]
Thank you @matdehaast , you mean, we should keep them alive within the container?

**Comment by dora-gt** [comment]
@nhartner Is this still what you'd need? or `testnet-bundle` or something satisfies your requirements?

**Comment by nhartner** [comment]
Closing because `ilp-node` docker image addresses my needs.
