### ISSUE TITLE
Make examples use CLI args vs env vars consistently

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#335]
@gakonst pointed out that they're mixed right now in https://github.com/interledger-rs/interledger-rs/blob/master/examples/eth-settlement/README.md

**Comment by dora-gt** [comment]
Maybe I think we should use CLI arguments **basically** (other than secret ones) because I suppose people would use ENV vars to override settings.

So I'll change this to use CLI arguments consistently.

**Comment by emschwartz** [comment]
Can this be closed?

**Comment by dora-gt** [comment]
Yes, I'll close.
