### ISSUE TITLE
Try boxing interledger services to speed up compilation

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#340]
Building the node is very slow, possibly due to all the generics involved in compiling the nested services.

We should try adding a `.boxed()` method to the `interledger_service::{IncomingService, OutgoingService}` like `warp` has for filters to see if it speeds up the compilation.

If that does speed up compilation, we should make it so the services are boxed in debug builds but not for release builds.

**Comment by emschwartz** [comment]
@bstrie you concluded that this didn't make a difference, right? Can this be closed now?

**Comment by bstrie** [comment]
Indeed, the approaches I tried didn't seem to make significant difference. I'd like to revisit this after we switch to async/await if ilp-node is still a compilation bottleneck by then, and in the meantime we can explore other options (e.g. #391).

**Comment by emschwartz** [comment]
Ok I'll take this out of the current project then

**Comment by koivunej** [comment]
I think at the moment all services are in fact boxed and return boxed futures, this issue must be related to pre stable async/await in rust.
