### ISSUE TITLE
Move the interledger-settlement-engines to its own repo

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#343]
Should we:
- Put each settlement engine in a separate crate (to avoid having one binary and using conditional compilation to avoid pulling in dependencies when they aren't needed)
- Move the settlement engines to a separate repo under `interledger-rs` (but keep multiple engines in the same repo so they can easily share the core code)
- Move the settlement engines to a repo or organization where engines written in other languages will also live

cc @gakonst

**Comment by gakonst** [comment]
I'm in favor of 2.
-  Conditional compilation does not really add much complexity imo. 
- I'd rather not have a repo with multiple languages, and a new organization doesn't seem to make sense to me
- I prefer having a directory where each engine is its own subdirectory, the way it is now, I find it extensible and nice.

**Comment by emschwartz** [comment]
:+1: Let's put them in an `interledger-settlement-engines` (`-rs`?) repo under `interledger-rs`.

Instead of making them a single binary, let's put each in its own crate and make each one a separate binary.

**Comment by gakonst** [comment]
`interledger-rs-settlement-engines`? I do not have permissions to create a new repo btw

**Comment by emschwartz** [comment]
Created https://github.com/interledger-rs/settlement-engines
