### ISSUE TITLE
Improve account creation API and errors

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#364]
- If you try to create an account with fields that conflict with another account (e.g. same username), you get a 500 error instead of a 400 error
- The `PUT /accounts/:username` cannot be used to insert accounts, only modify existing ones. This is somewhat annoying if you are working on inserting and modifying a given account because you first need to call `POST /accounts` and then `PUT /accounts/:username` instead of being able to call `PUT /accounts/:username` from the start

**Comment by gakonst** [comment]
> If you try to create an account with fields that conflict with another account (e.g. same username), you get a 500 error instead of a 400 error

This has to do with our store traits not returning any meaningful error.

> The PUT /accounts/:username cannot be used to insert accounts, only modify existing ones. This is somewhat annoying if you are working on inserting and modifying a given account because you first need to call POST /accounts and then PUT /accounts/:username instead of being able to call PUT /accounts/:username from the start

This does not make much sense to me, what does insert & modify an account mean? You'd just insert it with the correct info
