### ISSUE TITLE
Balance API should include asset details

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#376]
It's hard to know what you're looking at when you just get back the plain number. It might be nice to include the `asset_code` and `asset_scale` in the response

**Comment by kincaidoneil** [comment]
Better yet, also provide a human-readable string? e.g `0.00348 XRP`?

**Comment by emschwartz** [comment]
Do you think it should return a single string like that or are you suggesting combining the `balance` and `asset_scale` to just return a decimal number?

**Comment by kincaidoneil** [comment]
> Do you think it should return a single string like that or are you suggesting combining the balance and asset_scale to just return a decimal number?

Mmmmm, probably just combining the balance and asset_scale to a decimal number, and leaving the code as a separate field.
