### ISSUE TITLE
Make credential retrieval programmatic

### ISSUE THREAD

**Issue by austin-king** [interledger-rs/interledger-rs#384]
https://xpring.io/ilp-testnet-creds allows you to retrieve credentials for ETH and XRP, however it would have been great for the Berkeley hackathon if these credentials could be returned as a JSON object in response to a simple HTTP GET request. I would have been able to auto populate default accounts for new users of my project if they didn't have pre-existing accounts that they wanted wanted to copy and paste in.

**Comment by emschwartz** [comment]
You can actually make the same call the website makes by GETting https://xpring.io/api/accounts/xrp (or https://xpring.io/api/accounts/eth). I wouldn't necessarily count on that API staying stable forever but that's what powers it now.

Also, did you see the [`ilp-cli testnet setup`](https://github.com/interledger-rs/interledger-rs/blob/a79a32c5186ccecd5ad3a1578d1c75bca10b7a0d/crates/ilp-cli/src/interpreter.rs#L294-L351) command? That's what the `interledgerrs/testnet-bundle` is using. It makes the call to the Xpring API and then creates the account on the local node for the testnet node.
