### ISSUE TITLE
Add missing routes to HTTP API docs

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#388]
- Deleting accounts
- Updating settings
- Incoming notifications

**Comment by dora-gt** [comment]
Oops! I accidentally did this issue. I misunderstood like that this was assigned to me 😞 Anyway, @bstrie please use [this branch](https://github.com/interledger-rs/interledger-rs/tree/feature/dx/update-documents) freely.

**Comment by bstrie** [comment]
@dora-gt Don't worry, I got sidetracked last week anyway and your version is better than mine. :) If you want to take this you can feel free to do this yourself.

**Comment by dora-gt** [comment]
OK, I'll take this.

**Comment by dora-gt** [comment]
I'm closing this since #444 has been merged.
