### ISSUE TITLE
Add copy/paste-able `curl` and `ilp-cli` examples to HTTP docs

### ISSUE THREAD

**Issue by bstrie** [interledger-rs/interledger-rs#389]
In the interest of lowering the barrier to entry as much as possible, rather than merely having the HTTP docs mention the parameters to each endpoint, I suggest having lines that the user can copy/paste into their terminal to show what an example of a well-formed command *should* look like (though obviously we'll need to make it clear that the command itself may not successfully execute unless their node is set up in a certain way). Consider as well having copy/paste-able lines for doing each operation in popular web frameworks/programming languages.

**Comment by gakonst** [comment]
Given that the HTTP API is now readily available via OpenAPI, can this be closed? Swagger provides `curl` commands: https://app.swaggerhub.com/apis/interledger-rs/Interledger/

**Comment by bstrie** [comment]
Sounds good to me.
