### ISSUE TITLE
Investigate hackathon error when sending payments to testnet

### ISSUE THREAD

**Issue by bstrie** [interledger-rs/interledger-rs#390]
Near the very end of the October 2 hackathon we suddenly had two teams independently approach us saying that they could not successfully call the `POST /accounts/:username/payments` endpoint. I suspect that the sudden onset of the problem was not to do with anything changing on the testnet itself, but rather that sending payments was the final step in each of these teams' projects and that this was their first attempt at actually doing so. 

Originally we attempted to diagnose the error by having them issue payments from their machines via `ilp-cli`, which worked as expected, but we continued to observe that they could not issue the payments when speaking to the HTTP API directly (one team was issuing requests via Go's built-in http client, and the other was using Postman).

Upon looking at the hackathon instructions for interacting with the testnet, I noticed that it advised users to send `username:username` as the authorization token for issuing a payment. I realized that this meant than a successful invocation of `ilp-cli`, given the user `alice` and an auth token of `alice:alice`, would actually have been sending a final auth token of `alice:alice:alice` (this behavior can be seen at https://github.com/interledger-rs/interledger-rs/blob/43dc677f7657a43bcbdc524bf4728f061df994cf/crates/ilp-cli/src/interpreter.rs#L221 , and is inherited from when `ilp-cli` was designed by looking at the `curl` requests in our examples; should this be changed?). I had thought that making the manual HTTP request send `username:username:username` as the auth token would fix the problem, but surprisingly it did not. I asked one of the users to install Wireshark and we confirmed that `ilp-cli` was sending an auth token of `username:username:username`, but replicating this via other clients, even when apparently identical according to Wireshark readouts, remained unsuccessful. Given the very short deadline the teams were more interested in finding workarounds (such as shelling out to `ilp-cli`, which worked) than further diagnosing the issue, so this is all the data I was able to gather.

After this I went around to all the other teams and asked if they were having any similar problems. None of them were, although I'm unsure if this is simply because 1) their demo did not involve hitting the payment endpoint or 2) they had tried to hit the payment endpoint earlier in the night and had already developed workarounds to failures they might have encountered.

I'm not sure how easily reproducible this is, but it's worth keeping an eye out for.

**Comment by gakonst** [comment]
We've changed the way credentials are parsed (username:password format is no longer used), so closing this
