### ISSUE TITLE
STREAM Receiver: Start sending ConnectionAssetDetailsFrame on first connection

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#395]
The [STREAM RFC](https://github.com/interledger/rfcs/blob/master/0029-stream/0029-stream.md#5314-connectionassetdetails-frame) defines an optionally-present frame called `ConnectionAssetDetails` that can be used to indicate the asset type/scale for the receiving account. 

The StreamReceiver MUST return `ConnectionAssetDetails` frame whenever it encounters a `ConnectionNewAddress` frame, likely [somewhere near here](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-stream/src/server.rs#L223) in order to allow new bidirectional streams to be opened up _after_ a Connection has been initiated.

**Comment by gakonst** [comment]
This is fixed in master in https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-stream/src/server.rs#L251-L260 and
