### ISSUE TITLE
Update Verbiage for Redacted AccountDetails 

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#397]
When getting account details, certain information is redacted, such as the `ilp_over_http_incoming_token`. When I first encountered this, I mistakenly thought the Connector was ignoring my input for these fields and instead replacing it with the String `SECRET`.

I propose clarifying this to something a bit more obvious, such `********` or `******** (redacted)`. For example: 

```json
{
    "id": "102e28b0-79bd-4454-b2ea-7aa2230314c2",
    "username": "user_hlcxojmp",
    "ilp_address": "test.xpring-dev.rs3.user_hlcxojmp",
    "asset_code": "XRP",
    "asset_scale": 9,
    "max_packet_amount": 1000,
    "min_balance": null,
    "ilp_over_http_url": null,
    "ilp_over_http_incoming_token": "******** (redacted)",
    "ilp_over_http_outgoing_token": "******** (redacted)",
    "ilp_over_btp_url": null,
    "ilp_over_btp_incoming_token": "******** (redacted)",
    "ilp_over_btp_outgoing_token": "******** (redacted)",
    "settle_threshold": 10000,
    "settle_to": 0,
    "routing_relation": "Child",
    "round_trip_time": 500,
    "packets_per_minute_limit": null,
    "amount_per_minute_limit": null,
    "settlement_engine_url": "http://settlement-xrp1-internal.xpring.dev:3000/"
}
```

**Comment by gakonst** [comment]
This is due to using [Secrecy which hardcodes that.](https://github.com/iqlusioninc/crates/blob/develop/secrecy/src/lib.rs#L113)

@tarcieri can we adjust it in some way?

**Comment by tarcieri** [comment]
You can either make your own wrapper type which impls `DebugSecret` or we can change the upstream message. I agree`REDACTED` would be better

**Comment by tarcieri** [comment]
`secrecy` v0.5.1 is out with this change
