### ISSUE TITLE
Error building interledger-settlement-engines package

### ISSUE THREAD

**Issue by KevinWMatthews** [interledger-rs/interledger-rs#403]
I'm having difficulty building the `interledger-settlement-engines` package as directed by the main README. Does anyone else experience the same thing?

If I follow the instructions from the [run subsection](https://github.com/interledger-rs/interledger-rs#run-1) under "Building From Source", I get the error:

```
$ cargo run -p interledger-settlement-engines -- ethereum-ledger
error: package `interledger-settlement-engines` is not a member of the workspace
```

I wonder if this also affects the settlement engine dockerfile, [`eth-se.dockerfile`](https://github.com/interledger-rs/interledger-rs/blob/master/docker/eth-se.dockerfile).

I tried building it with:

```
$ docker build --tag interledger-settlement-engines --file docker/eth-se.dockerfile .
Sending build context to Docker daemon  23.02MB
Step 1/13 : FROM clux/muslrust:stable as rust
 ---> 38c55d4f93f0
Step 2/13 : WORKDIR /usr/src
 ---> Using cache
 ---> 72223b6de00e
Step 3/13 : COPY ./Cargo.toml /usr/src/Cargo.toml
 ---> Using cache
 ---> 00d4b56ba82f
Step 4/13 : COPY ./crates /usr/src/crates
 ---> Using cache
 ---> 3d31f0f32346
Step 5/13 : RUN cargo build --release --package interledger-settlement-engines
 ---> Running in dda203758b40
    Updating crates.io index
error: package ID specification `interledger-settlement-engines` matched no packages
The command '/bin/sh -c cargo build --release --package interledger-settlement-engines' returned a non-zero code: 101
```

I see a package named `interledger-settlement` but not `interledger-settlement-engines`.

I'm not sure what to build instead; there seem to only be two available binaries:

```sh
$ cargo run --bin
error: "--bin" takes one argument.
Available binaries:
    ilp-cli
    ilp-node
```

**Comment by emschwartz** [comment]
Ah sorry! That was just moved to its own repo in https://github.com/interledger-rs/interledger-rs/pull/394 They're now in https://github.com/interledger-rs/settlement-engines

@gakonst could you update the documentation to reflect this change?

**Comment by KevinWMatthews** [comment]
Ah! Makes sense.
Should the [ethereum settlement engine Dockerfile](https://github.com/interledger-rs/interledger-rs/blob/master/docker/eth-se.dockerfile) move to that repo as well?

**Comment by gakonst** [comment]
Should be fixed in https://github.com/interledger-rs/interledger-rs/pull/414 and https://github.com/interledger-rs/settlement-engines/commit/f7f07916971488a1289d0c6b02749214a092f8a3
