### ISSUE TITLE
Any plan to update `ring` dependency to latest version?

### ISSUE THREAD

**Issue by calvinaco** [interledger-rs/interledger-rs#407]
The latest version of `ring` is [0.16.9](https://docs.rs/ring/0.16.9/ring/) but this repository and the `settlement-engines` repository is still using `0.14.6`.

This causes a problem when I try to implement a settlement engine by including my own project as a crate in `Cargo.toml`.

```
error: failed to select a version for `ring`.
    ... required by package `rustls v0.16.0`
    ... which is depended on by `{my-project}`
    ... which is depended on by `interledger-settlement-engines v0.1.1-beta.2`
versions that meet the requirements `^0.16.5` are: 0.16.9, 0.16.7, 0.16.6, 0.16.5

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.14.6`
    ... which is depended on by `ilp-node v0.4.1-beta.2`
    ... which is depended on by `interledger-settlement-engines v0.1.1-beta.2`
    ...
```

I understand this update is optional to this repository but I would like to know if there is any plan on doing so? Thank you.

**Comment by emschwartz** [comment]
For sure! The main issue is that there was a breaking change to the API so it's a bit of a pain to update. (PRs welcome if you want to expedite this! :wink:)
