### ISSUE TITLE
ILP-over-HTTP Endpoint returns incorrect error code when Unauthorized

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#415]
When an unauthorized ILP-over-HTTP call is made to the Connector, the Connector errantly responds with an HTTP error `500`. Instead, the Connector should respond with an HTTP `401` error code.

*UnAuthorized Request*
```
Request{method=POST, url=https://rs3.xpring.dev/ilp, headers=[Accept:application/octet-stream, Content-Type:application/octet-stream, Cache-Control:private, max-age=0, no-cache, Pragma:no-cache, ILP-Operator-Address:test.xpring-dev.rs3.user_hj1tmc3b, Authorization:Bearer user_hj1tmc3b:lzjtsi4ny5f09]}
```

*Response* 
```
Response{protocol=h2, code=500, message=, url=https://rs3.xpring.dev/ilp}
Message: Unauthorized
```

**Comment by KevinWMatthews** [comment]
Could this be stem from [here](https://github.com/interledger-rs/interledger-rs/blob/4653a7bed661784579be6aa3b5dccab53b37f78c/crates/interledger-http/src/server.rs#L72) and [here](https://github.com/interledger-rs/interledger-rs/blob/4653a7bed661784579be6aa3b5dccab53b37f78c/crates/interledger-http/src/server.rs#L62) in the interledger http server?

It looks like warp's [docs](https://docs.rs/warp/0.1.20/warp/reject/fn.custom.html) and [error.rs](https://github.com/seanmonstar/warp/blob/0828822e834d6837091813ad3efe2a03a17d0da7/examples/errors.rs#L48) example add a [`recover`](https://docs.rs/warp/0.1.20/warp/trait.Filter.html#method.recover) call to return errors other than 500, but I'm still coming up to speed on warp (warp speed?) and this section of interledger-rs.

**Comment by emschwartz** [comment]
This should be resolved by https://github.com/interledger-rs/interledger-rs/pull/324

Can you try the calls on that branch?

**Comment by dora-gt** [comment]
Maybe that would not be solved, I mistakingly applied my changes only to HTTP APIs. I should've applied to ILP over HTTP too. I'll fix this issue on the branch.

**Comment by gakonst** [comment]
@sappenin closing this as it should be fixed in https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-http/src/server.rs#L57. Please re-open if you still observe this error
