### ISSUE TITLE
Account models should be explained in an understandable way.

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#416]
There are a few account models but these are not explained anywhere, which makes ILP confusing IMO (explained only in RFC).

1. Non-routing account model
    - The account is not connected to any outer connectors.
    - The account holder could easily send/receive payments.
1. Delegated account model (`child`/`parent` or `peer`)
    - The account is connected to an outer connector.
    - On the other connector, it has an account which represents our account.
    - This is used for routing.

**Comment by gakonst** [comment]
Can we close this? I describe this in https://github.com/interledger-rs/interledger-rs/blob/master/docs/peering.md#routing-relations

**Comment by gakonst** [comment]
Closing, feel free to re-open if you think my description in the docs is not enough
