### ISSUE TITLE
Should we separate the admin and user APIs more?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#417]
Right now the HTTP API combines both admin and user-facing APIs. Should we separate them out (into separate paths, separate crates, or separate ports) or keep them together?

**Comment by gakonst** [comment]
I do not mind leaving them as is, especially now that with the [Swagger specification](https://app.swaggerhub.com/apis/interledger-rs/Interledger/) we can quickly see which are the admin and which are the user-apis.
