### ISSUE TITLE
Default README instructions compile twice?

### ISSUE THREAD

**Issue by KevinWMatthews** [interledger-rs/interledger-rs#423]
What are the differences between running `ilp-node` and `ilp-cli` as a package versus a binary? The main README [directs the user to run](https://github.com/interledger-rs/interledger-rs#run-1) both as a package. When I run as a package, I see parts of the project recompile even though a full build is complete.

For example, running as a binary behaves as I expect:

```sh
$ cargo clean

$ cargo build
   # ...
   Compiling ilp-cli v0.1.1-beta.1
   # ...
   Compiling ilp-node v0.4.1-beta.3
    Finished dev [unoptimized + debuginfo] target(s) in 1m 53s

# Runs immediately
$ cargo run --bin ilp-node
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/ilp-node`

# Also runs immediately
$ cargo run --bin ilp-cli
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/ilp-cli`
```

while running as a package recompiles several dependencies:

```sh
$ cargo clean

$ cargo build
   # ...
   Compiling ilp-cli v0.1.1-beta.1
   # ...
   Compiling ilp-node v0.4.1-beta.3
    Finished dev [unoptimized + debuginfo] target(s) in 1m 50s

# Compiles again
$ cargo run -p ilp-node
   Compiling memchr v2.2.1
   Compiling aho-corasick v0.7.6
   # ...
   # Does not compile ilp-cli
   # ...
   Compiling ilp-node v0.4.1-beta.3
    Finished dev [unoptimized + debuginfo] target(s) in 1m 02s
     Running `target/debug/ilp-node`

# Also compiles again
$ cargo run -p ilp-cli
   Compiling log v0.4.8
   Compiling syn v0.15.44
   # ...
   Compiling ilp-cli v0.1.1-beta.1
    Finished dev [unoptimized + debuginfo] target(s) in 17.10s
     Running `target/debug/ilp-cli`
```

Does anyone else see the same thing? I'm not sure why cargo does this. It isn't terrible, but as a user I expect the compile step to be complete.

If there's no difference, the error output of `--bin` provides helpful information to the user:

```
$ cargo run --bin
error: "--bin" takes one argument.
Available binaries:
    ilp-cli
    ilp-node
```

compared to:
```
$ cargo run -p
error: The argument '--package <SPEC>' requires a value but none was supplied

USAGE:
    cargo run --package <SPEC>
```

**Comment by gakonst** [comment]
I think this is a rust/cargo issue, is it within our control?

**Comment by bstrie** [comment]
I believe this happens because cargo only looks to reuse artifacts when all the inputs are exactly the same, including compilation flags such as `-p`. I'm not sure why we tell people to build with `-p`, but AFAICT it should be unnecessary.
