### ISSUE TITLE
ilp-node panics with invalid config argument

### ISSUE THREAD

**Issue by KevinWMatthews** [interledger-rs/interledger-rs#425]
If the user passes an invalid config file to the `ilp-node` executable, the program panics:

```
$ cargo run -p ilp-node -- bad-config-file
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "bad-config-file" not found', src/libcore/result.rs:1084:5
```

The stack trace blames the `unwrap()` call in [this line](https://github.com/interledger-rs/interledger-rs/blob/1a5312ac12ed55b8910db7ba84e1b93ad6cb389a/crates/ilp-node/src/main.rs#L136).

Simply omitting `-p` or `--bin` causes the same error:

```
$ cargo run ilp-node
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "ilp-node" not found', src/libcore/result.rs:1084:5
```

This seems to be due to the [default-run](https://github.com/interledger-rs/interledger-rs/blob/1a5312ac12ed55b8910db7ba84e1b93ad6cb389a/crates/ilp-node/Cargo.toml#L9) setting: the `ilp-node` binary is run by default, so the command-line argument "ilp-node" is parsed as the config file's name.

I'd like to find a way to print a reasonable way to display an error message to the user. What is your approach to error handling in this context?

**Comment by dora-gt** [comment]
Actually I'd like to address this kind of issue in a more comprehensive way, like `rustc`.
`rustc` always tells us what was the problem with what we should do. That's why I love `rustc`.
I'd want to take on this issue along with #317.
