### ISSUE TITLE
Add tags to docker images instead of only having latest version on dockerhub

### ISSUE THREAD

**Issue by nhartner** [interledger-rs/interledger-rs#427]
Currently the docker images in interledgerrs are not tagged so it's only possible to pull the latest version (ex. https://hub.docker.com/r/interledgerrs/node/tags). Occasionally there have been backward breaking changes to the Rust APIs so it would be nice if the images were tagged so that I could pull a specific version until we are able to update our code to deal with changes in newer versions.

**Comment by gakonst** [comment]
Can this be closed? #506 takes care of tagging if i'm not mistaken @dora-gt

**Comment by dora-gt** [comment]
Thanks, yes, it will be tagged as the same version as the `ilp-node` crate version.
Commits on the `master` branch will be tagged as `latest` on the other hand.

**Comment by nhartner** [comment]
I'm still only seeing a single tag "latest" in dockerhub: https://hub.docker.com/r/interledgerrs/ilp-node/tags

**Comment by dora-gt** [comment]
Hi Neil,

That's because any other releases haven't been made after the CI process was merged.
Would you need older tags?

**Comment by sappenin** [comment]
Hi @dora-gt yes, we have a Java build that relies upon a specific version of the Rust Connector. When the Rust connector changes, our build breaks.

I'm not sure what the easiest fix here is for you - maybe make an intermediate release of the Rust Connector that the Java team can rely on until the v0.9/v1.0 of the Rust Connector is released?

**Comment by nhartner** [comment]
An initial release tag would be nice. There was backwards incompatible change made here https://github.com/interledger-rs/interledger-rs/commit/e3cb7d1fb2b02a04bf0c945309055bd7048aa531
Since there is only a "latest" version our integration tests started breaking. I've fixed our integration tests to work with the new changes so not a high priority. But having a immutable, tagged image would prevent this from happening again.
