### ISSUE TITLE
Congestion Control may panic when in flight amount is larger than max

### ISSUE THREAD

**Issue by calvinlauco** [interledger-rs/interledger-rs#430]
During congestion control, the maximum in-flight amount will be decreased on rejection and at one point the `max_in_flight` may fall below `amount_in_flight`, which will cause the `get_max_amount` method below to panic with: `attempt to subtract with overflow`

crates/interledger-stream/src/congestion.rs
```
    pub fn get_max_amount(&mut self) -> u64 {
        let amount_left_in_window = self.max_in_flight - self.amount_in_flight;
        if let Some(max_packet_amount) = self.max_packet_amount {
            min(amount_left_in_window, max_packet_amount)
        } else {
            amount_left_in_window
        }
    }
```

**Comment by emschwartz** [comment]
Resolved by https://github.com/interledger-rs/interledger-rs/pull/431
