### ISSUE TITLE
Convert examples to use ilp-cli rather than curl when in docker mode

### ISSUE THREAD

**Issue by bstrie** [interledger-rs/interledger-rs#443]
The examples are currently using ilp-cli when in non-docker mode, but are still using curl in docker mode. I can make this change since I'm the one who translated the non-docker mode to ilp-cli in the first place, but I'll wait for PR #305 to land first so as to avoid stepping on anyone's toes.

**Comment by dora-gt** [comment]
IMO, we should be careful about using `ilp-cli` for docker mode because it looks a bit slow. Maybe takes 1sec or so. It might be because of `--rm` option but I think we need the option because without the option, garbage containers remain forever.

**Comment by bstrie** [comment]
@dora-gt Actually the reason why the ilp-cli looks slow is because of https://github.com/interledger-rs/interledger-rs/pull/405 , which moved from invoking the ilp-cli binary directly to running it through `cargo run`. Cargo will check to make sure the code doesn't need to be recompiled before each and every command, which adds about a second of overhead to each invocation. Conceivably docker mode could use the previous approach where we invoked the ilp-cli binary directly (which is very fast), because the reason we changed is that we wanted users to be able to run `run-md.sh` from any directory in the repo (which `cargo run` gives us for free), but docker mode (I assume?) could just use a hardcoded path to the binary without any problems.

**Comment by dora-gt** [comment]
I'm sorry that my comment was not clear. I don't mean that `ilp-clip` is slow. I mean using the docker image of `interledgerrs/ilp-cli` is slow, which requires creating a new container and finally cleaning up the container.

**Comment by bstrie** [comment]
Interesting, does this imply that it has to set up and tear down an `ilp-cli` container for each and every `ilp-cli` invocation? What can we do to make it behave more like `curl` currently does, where no such set up and tear down is necessary?

**Comment by dora-gt** [comment]
If my recognition is correct, that's right. I've tried some and looked into a little bit, I could not make it. I think making it fast like `curl` is very difficult as long as we use Docker.

That said, I'm saying only from my experience and a quick reseatch, I would really appreciate your taking a look if reusing containers is possible or not.

**Comment by bstrie** [comment]
I suppose I don't understand why Docker would treat `curl` any differently than `ilp-cli`. From Docker's point of view they're both just external binaries. Does every Docker container ever built come with `curl` built in? (That wouldn't make any sense to me.)

I have no experience with Docker, can you help explain something for me? In the line here: https://github.com/interledger-rs/interledger-rs/blame/bf9e50eaf2299995b52d1246a18fd263bef6ab67/examples/simple/README.md#L111 we run the binary with `docker run`, but two lines afterward we just execute `redis-server` as normal. Why does one need to be run through Docker where the other one can just be run normally?

**Comment by emschwartz** [comment]
I think this can be closed once https://github.com/interledger-rs/interledger-rs/pull/506 is merged

**Comment by gakonst** [comment]
Closing, since #506 got merged
