### ISSUE TITLE
Some of settlement APIs seem to return incorrect HTTP status codes.

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#446]
In the RFC, it defines that basically `POST` endpoints should return `201` HTTP status codes but `send_money`, `receive_message`, `do_receive_settlement` and `do_send_outgoing_message` seem to return `200`.

Sorry if I'm missing something.

**Comment by gakonst** [comment]
Now that the RFC is merged in master I'll be doing a pass through  this week to resolve any inconsistencies.

**Comment by emschwartz** [comment]
@gakonst Can this be closed now?

**Comment by emschwartz** [comment]
@gakonst ping

**Comment by gakonst** [comment]
Yeah this was fixed in https://github.com/interledger-rs/interledger-rs/pull/507
