### ISSUE TITLE
Explain typical usage of `messages` would be helpful.

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#447]
In the [settlement RFC](https://github.com/interledger/rfcs/blob/master/0038-settlement-engines/0038-settlement-engines.md#handle-incoming-message), messages are defined but it is not explained well.
Explaining typical usage or implementation would be helpful.

**Comment by gakonst** [comment]
The point of the RFC was that there is no need for the messages to have any format, and leave it up to the engine to handle it per imnplementation! (Closing)
