### ISSUE TITLE
Document our minimum Rust version

### ISSUE THREAD

**Issue by bstrie** [interledger-rs/interledger-rs#449]
Currently it's unclear what minimum version of Rust is required to build Interledger.rs. Today the answer is probably "whatever the most recent stable release is", but we could conceivably do better at not requiring dependent users to always promptly update their Rust versions. This would require us to be careful when writing code that we don't use features that only exist on Rust versions that are newer than our desired minimum version. We could enforce this by having CI compile using the minimum version.

Note that we're definitely going to want to begin using async/await syntax when it releases in 1.39, so that could be the version at which we begin enforcing this (in other words, we could promise that anyone using Rust 1.39 can continue using Rust 1.39 for some reasonable amount of time after it is no longer the most recent Rust version).

**Comment by gakonst** [comment]
Agree we should flag 1.39 once we switch to async/await

**Comment by gakonst** [comment]
https://github.com/rust-lang/rust/issues/65262
