### ISSUE TITLE
Would adding a debug_boxed method on the Interledger service traits speed up compile time?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#463]
We should see if adding a `debug_boxed` method along the lines of what I proposed in https://github.com/seanmonstar/warp/pull/273 would speed up the compile time of the node. The `warp` maintainer's main concern was that it's strange to have a methods return type depend on what type of build it is. In our case, we know that the services are only used in a generic way, so adding this isn't a problem.

That said, it's only worth doing if it actually speeds up the compile times.

**Comment by gakonst** [comment]
@emschwartz I believe we tried this already to no avail. @bstrie you think it's worth further investigation, based on the discussion we had with the Tower people in Rustfest?

**Comment by bstrie** [comment]
I'm convinced that there is *some* way to add boxing in order to speed up compilation, though we have a lot of other refactors to consider as well (like async/await), so this may something to leave until later.

**Comment by emschwartz** [comment]
Alright let's close this for now
