### ISSUE TITLE
STREAM: Retry R00 Errors

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#467]
In [this test](https://circleci.com/gh/interledger-rs/interledger-rs/2641) run, the STREAM client stopped because of an R00 error:

```
[DEBUG interledger_stream::client] Prepare 1 with amount 2000 was rejected with code: R00 (2000 left to send)
[ERROR interledger_stream::client] Send money stopped because of error: SendMoneyError("Packet was rejected with error: R00 ")
[ERROR interledger_spsp::client] Error sending payment: SendMoneyError("Packet was rejected with error: R00 ")
```

I'm not sure why it timed out, but in any case the STREAM sender should retry on `RXX` errors.

**Comment by dora-gt** [comment]
Just taking a glance at this problem, I think these lines are causing the behavior.

https://github.com/interledger-rs/interledger-rs/blob/d6f5c748e0610e2ff7ee7446591ef20e900f3b63/crates/interledger-stream/src/client.rs#L387

https://github.com/interledger-rs/interledger-rs/blob/d6f5c748e0610e2ff7ee7446591ef20e900f3b63/crates/interledger-stream/src/client.rs#L270

Referring to the [ILPv4 RFC](https://github.com/interledger/rfcs/blob/master/0027-interledger-protocol-4/0027-interledger-protocol-4.md#r__---relative-error), 

> Relative errors indicate that the payment did not have enough of a margin in terms of money or time. However, it is impossible to tell whether the sender did not provide enough error margin or the path suddenly became too slow or illiquid. The sender MAY retry the payment with a larger safety margin.

We could retry for this error but we have to consider the strategy on it to amend the margin.

1. How often we should retry
1. When we should give up retrying

I'm not sure in this case we should adopt some strategies like exponential backoff, I think just retrying some predefined times and then giving up are sufficient, at least for `R00` error.

Also I don't think we should retry for ``

**Comment by dora-gt** [comment]
(Sorry I wrongly pushed close button)
