### ISSUE TITLE
Crash waiting for settlement 

### ISSUE THREAD

**Issue by treisto** [interledger-rs/interledger-rs#484]
Amount to send 1200
settlement threshold 500
min balance -1000
we still have 200 to send while waiting for the previous 2x500 settlements to be validated on the ledger
the sender tries to send them while the receiver still rejects because its max malance is still -1000
at some point the sender crashes

[DEBUG interledger_stream::congestion] Prepare packet of 10, amount in flight is now: 200
[TRACE interledger_router::router] Found matching route for address: "g.rust_uni_oct_1.iTZqr3STChL7g1cRnDc6dUTIzYjlMSuOZoZ3NVMeJJ4". Prefix: "g.rust_uni_oct_1", account: 051e3cf7-aaba-411b-8719-cc6b01305acc
[TRACE interledger_store_redis::store] Processed reject for incoming amount: 10. Account 61170b92-381d-4148-bb9c-09f39409c248 has balance (including prepaid amount): -1190
[TRACE interledger_store_redis::store] Processed reject for incoming amount: 10. Account 61170b92-381d-4148-bb9c-09f39409c248 has balance (including prepaid amount): -1170
[TRACE interledger_store_redis::store] Processed reject for incoming amount: 10. Account 61170b92-381d-4148-bb9c-09f39409c248 has balance (including prepaid amount): -1180
[TRACE interledger_service_util::exchange_rates_service] Converted incoming amount of: 10 XRP (scale 6) from account 61170b92-381d-4148-bb9c-09f39409c248 to outgoing amount of: 10 XRP (scale 6) for account 051e3cf7-aaba-411b-8719-cc6b01305acc
[TRACE interledger_service_util::exchange_rates_service] Converted incoming amount of: 10 XRP (scale 6) from account 61170b92-381d-4148-bb9c-09f39409c248 to outgoing amount of: 10 XRP (scale 6) for account 051e3cf7-aaba-411b-8719-cc6b01305acc
[TRACE interledger_service_util::exchange_rates_service] Converted incoming amount of: 10 XRP (scale 6) from account 61170b92-381d-4148-bb9c-09f39409c248 to outgoing amount of: 10 XRP (scale 6) for account 051e3cf7-aaba-411b-8719-cc6b01305acc
[DEBUG interledger_stream::congestion] Rejected packet with T04 error. Amount in flight was: 200, decreasing max in flight to: 256
[DEBUG interledger_stream::client] Prepare 157 with amount 10 was rejected with code: T04 (10 left to send)
[DEBUG interledger_stream::congestion] Rejected packet with T04 error. Amount in flight was: 190, decreasing max in flight to: 128
[DEBUG interledger_stream::client] Prepare 158 with amount 10 was rejected with code: T04 (20 left to send)
[DEBUG interledger_stream::congestion] Rejected packet with T04 error. Amount in flight was: 180, decreasing max in flight to: 64
[DEBUG interledger_stream::client] Prepare 159 with amount 10 was rejected with code: T04 (30 left to send)
[DEBUG interledger_stream::congestion] Rejected packet with T04 error. Amount in flight was: 170, decreasing max in flight to: 32
[DEBUG interledger_stream::client] Prepare 161 with amount 10 was rejected with code: T04 (40 left to send)
[DEBUG interledger_stream::congestion] Rejected packet with T04 error. Amount in flight was: 160, decreasing max in flight to: 16
[DEBUG interledger_stream::client] Prepare 162 with amount 10 was rejected with code: T04 (50 left to send)
thread 'interledger-rs-worker-0' panicked at 'attempt to subtract with overflow', crates/interledger-stream/src/congestion.rs:57:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by emschwartz** [comment]
I think this was fixed by https://github.com/interledger-rs/interledger-rs/pull/431 and this fix was included in the latest release. If you're using the docker image, try pulling it again (I just realized that docker doesn't update the `:latest` tag unless you explicitly tag an image with that and push it so the `testnet-bundle` image is now updated).

**Comment by gakonst** [comment]
Closing this as it should be fixed. @treisto feel free to re-open if you re-encounter it on latest master!
