### ISSUE TITLE
Wrong error code (F08) used when request.prepare.amount is too small

### ISSUE THREAD

**Issue by latenssi** [interledger-rs/interledger-rs#499]
In [exchange_rates_service](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-service-util/src/exchange_rates_service.rs) if the `request.prepare.amount` is so small that the conversion to `outgoing_amount` results in a float between 0 and 1 the `exchange_rates_service` will return **Error F08 "Amount Too Large"** as specified on [this line](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-service-util/src/exchange_rates_service.rs#L148). 

I think this is misleading. In my opinion the result in this case should be **Error F03 "Invalid Amount"** with an explanation as this happens when one tries to send an amount too small to be converted and relayed.

**Comment by kincaidoneil** [comment]
I think this case should return `R01`, Insufficient Source Amount.

Per the [ILPv4 spec](https://interledger.org/rfcs/0027-interledger-protocol-4/):

> The amount received by a connector in the path was too little to forward (zero or less). Either the sender did not send enough money or the exchange rate changed. The sender MAY try again with a higher amount, but they SHOULD NOT do this indefinitely or a malicious connector could steal money from them.

**Comment by latenssi** [comment]
@kincaidoneil I agree, that is a better error code

**Comment by bstrie** [comment]
Copying Evan's comment from #540:

> I don't think that's the right error. The problem here is that the amount is bigger than the max u64. You'd definitely want to communicate to the sender that they need to send a smaller amount in order for the packet to go through

**Comment by kincaidoneil** [comment]
@gakonst @bstrie @latenssi Didn't see this was caused by an overflow. I think your original suggestion of F03 makes more sense then!

**Comment by gakonst** [comment]
To be clear: The OP's statement "the  request.prepare.amount is so small that the conversion to outgoing_amount results in a float between 0 and 1" is not correct, this happens because when Rust casts a large f64 to u64, it zeroes it, if it was larger than what can fit in u64.
