### ISSUE TITLE
Update client.rs to use Outgoing Bearer token instead of AuthToken for outgoing IlpOverHttp requests.

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#500]
This relates to #357, but currently, if an IlpOverHttp account is configured with an `outgoing` bearer token, the Rust implementation is inferring token-format unnecessarily.

Per IlpOverHttp Auth Recs [here](https://github.com/interledger/rfcs/pull/559/files#diff-4b23f32e485ebb46ea9cf36892850ffbR44), the `token-user` (which is the Rust Connector when it's making outgoing IlpOverHttp requests to a peer) should treat auth tokens as opaque and not attempt to do any parsing of them. This will allow non-Rust connectors to construct token-schemes without needing to coordinate the scheme with any other ILP implementations (such as the Rust implementation, in this case).

One manifestation of this in today's code, for example, is if I configure an account on the Rust connector with an outgoing bearer token of `foo:bar:baz`. While this value will be stored into the database, the Rust implementation will attempt to parse this token into an `AuthToken`, which will assume the String adheres to that formatting -- the implementation will only send `foo:bar` to the peer, which will trigger an HTTP 401 error.

More formally, this issue requests to change `client.rs` to not use the current `AuthToken` when assembling its `Authorization` header, but instead simply use `token` as found [here](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-http/src/client.rs#L70).

**Comment by dora-gt** [comment]
Regarding the RFC, shouldn't we get rid of prefixing with usernames? It seems that `Bearer` tokens (`b64token`) don't allow `:` in its credentials. So our bearer tokens don't conform to normative `Bearer` tokens, which doesn't look nice. If we want to do so, we could issue paths per user like `/accounts/:username/ilp`. Then we could treat our tokens as totally opaque.

```
     b64token    = 1*( ALPHA / DIGIT /
                       "-" / "." / "_" / "~" / "+" / "/" ) *"="
     credentials = "Bearer" 1*SP b64token
```

Also, I'm curious about how we differentiate the type of authentication that the bearer sent? It seems that there are no type definitions in the `Authorization ` header.

Anyway, I'll look into.
