### ISSUE TITLE
IlpOverHttp IncomingTokens with a colon fail Auth

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#508]
If I create an account on the Rust connector and set the value of `ilp_over_http_incoming_token` to a String that contains a colon (`:`), then the account can't be used because auth will fail during parsing. For example:

```
{
    "username": "neil_test3",
    "routing_relation": "Peer",
...
    "ilp_over_http_url": "https://example.com",
    "ilp_over_http_incoming_token": "foo:bar",
    "ilp_over_http_outgoing_token": "foo",
...
}
```

The Connector should either disallow colons in the incoming token, or more preferably, mandate that the token be a base64-encoded String so that it can simply be treated as bytes.

To see this in action, try the following two requests:

# Works
```curl
curl -X GET \
  https://rs3.xpring.dev/accounts/test_david2 \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer test_david2:foobar' \
  -H 'Host: rs3.xpring.dev'
```

# Does not Work
```curl
curl -X GET \
  https://rs3.xpring.dev/accounts/test_david \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer test_david:foo:bar' \
  -H 'Host: rs3.xpring.dev'
```

**Comment by emschwartz** [comment]
This will be fixed when https://github.com/interledger-rs/interledger-rs/issues/550 is changed
