### ISSUE TITLE
Add an SQL-backed Store

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#52]
Possibly using [diesel](https://github.com/diesel-rs/diesel) so we can use support SQLite, Postgres, and MySQL.

Also create ways for the settlement engine(s) to interact with that store.

**Comment by cjimison** [comment]
For this ticket would you like to migrate all the storage calls in the Redis storage driver to an SQL based backend?  I was also going to add a command line flag and a config file option for using the SQL based storage instead of the Redis storage.

**Comment by emschwartz** [comment]
I was thinking that we would add another store that implements all of the same `_____Store` traits using SQL calls instead of Redis methods and scripts. Is that what you mean by migrating the storage calls?

A command line flag or env var for the Interledger node to use this store instead of Redis sounds good.

**Comment by cjimison** [comment]
That is correct.  I went with the tokio-postgres lib for now just because it fits the future model better and created a new crate called interledger-storage-postgres.  Just wanted to double check that this was to be an alternative storage model instead of a polyglot system, where some stuff was kept in redis and others in postgres.

**Comment by emschwartz** [comment]
Perfect! That's exactly what I was thinking

**Comment by gakonst** [comment]
Is anybody going to be working on this? It seems to be conflicting with https://github.com/interledger-rs/interledger-rs/issues/195 if we decide to go with it, since it'll result in a large refactor of the codebase.

**Comment by gakonst** [comment]
tokio-postgres had a 0.5 release, with async/await support. Seems to me like we could use it. 

@cjimison https://github.com/cjimison/interledger-rs/tree/feature/postgres I found this, but there's no postgres related code that I can see, could you perhaps push any of the work that you did, for reference? Thanks!

https://docs.rs/tokio-postgres/0.5.1/tokio_postgres/

**Comment by gakonst** [comment]
Closing in favor of #474
