### ISSUE TITLE
Should /ilp be moved to /accounts/:username/ilp ?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#521]
Right now we use the authorization to determine which account the packets are being sent for. We could continue doing that or it might make more sense to put that path under accounts, since the packets are being sent on behalf of a specific account.

This could be a breaking change but we could do it in a backwards-compatible way by supporting both in the meantime and deprecating the `/ilp` (and `/ilp/btp`).

Thoughts?

cc @gakonst @dora-gt

**Comment by matdehaast** [comment]
We initially had been using a singular `/ilp` but ended up changing towards an equivalent of `/accounts/:username/ilp`. The latter provides much more flexibility, especially when you are doing both authz and authn in two different steps.

**Comment by dora-gt** [comment]
I think we should adopt this approach as mentioned here https://github.com/interledger-rs/interledger-rs/issues/500#issuecomment-555370312 because now our bearer tokens don't seem to conform to normative ones.

**Comment by gakonst** [comment]
Fixed in https://github.com/interledger-rs/interledger-rs/pull/553
