### ISSUE TITLE
Routes update when deleting an account

### ISSUE THREAD

**Issue by leboiko** [interledger-rs/interledger-rs#534]
When deleting an account on the node the routes are not being updated.

**Comment by gakonst** [comment]
@leboiko could you give more context on the bug? Please provide a test case illustrating the behavior you are experiencing, and the behavior you expected to see!

**Comment by emschwartz** [comment]
I'm going to close this now but feel free to reopen if someone can document how to reproduce this issue and describe the desired behavior
