### ISSUE TITLE
Auth needs to be fixed.

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#550]
Desperately.

I tried to explain what values to set the `ilp_over_http_incoming_token` and corresponding option on the other node to to @austin-king and the current method of including the username in the token is crazy.

We need to prioritize:
- [x] Putting the username in the path https://github.com/interledger-rs/interledger-rs/issues/521
- [x] Getting rid of the code that parses the username from the bearer token
- [x] Documenting the format expected for the auth tokens in the API docs (is it hex, utf8, base64?)
- [x] Document how to peer two nodes together with explanations of how to set each of the fields or when they should be used

**Comment by gakonst** [comment]
I'm on #521, doing this in a backwards compatible way

**Comment by gakonst** [comment]
https://github.com/interledger-rs/interledger-rs/pull/553 fixes the first 2 tasks

- The Auth tokens can be anything format, so not sure if there is something to document here
- I'll add a `peering.md` under `docs/` describing how peering should work and when each field is necessary or not.

**Comment by emschwartz** [comment]
> The Auth tokens can be anything format, so not sure if there is something to document here

After #553 I agree it might not be necessary to specifically document the token format

> I'll add a peering.md under docs/ describing how peering should work and when each field is necessary or not.

Awesome

**Comment by gakonst** [comment]
Closing since #559 is merged
