### ISSUE TITLE
Convert Strings to SecretStrings

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#556]
As title. Also in a few places where we use `String` in Warp, they can be automatically converted via `Secrecy`'s `FromStr` implementation, after a new release is made.

_Originally posted by @gakonst in https://github.com/interledger-rs/interledger-rs/pull/553/review_comment/create_

**Comment by emschwartz** [comment]
Is this still blocked?

**Comment by gakonst** [comment]
Yeah, so the Secrecy version which includes that is `0.6` which updated `bytes` to `0.5` which itself had a few breaking changes. I am not sure yet how much effort is required, but would probably mean the whole repo needs to move to bytes `0.5`. @tarcieri do you think it'd be possible to make a minor Secrecy release as `0.5.2`, with https://github.com/iqlusioninc/crates/pull/309 in it?

**Comment by tarcieri** [comment]
Yeah, I can do that.

Also in a pinch you can include two different versions of bytes (I had to do that [in the tendermint crate](https://github.com/interchainio/tendermint-rs/blob/master/tendermint/Cargo.toml#L35) because Prost hasn't updated yet), but avoiding that is probably for the best.

**Comment by tarcieri** [comment]
Made a backport PR here: https://github.com/iqlusioninc/crates/pull/316

**Comment by tarcieri** [comment]
It's out: https://crates.io/crates/secrecy/0.5.2
