### ISSUE TITLE
interledger-service API review for v1.0-rc

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#569]
interledger-service public items marked with `x` are documented. Non-exported items are not taken into account. Follows format from #561. 

Part of #557.

- [x] `username` (struct)
- [x] `trace`(module): Does this need to be exported? It just contains implementations to the service traits for `Instrumented`
- [x] `Account` (trait)
   - Should we document each function's expected output? Their names are pretty self-explanatory.
- [x] `IncomingRequest` (struct)
   - Maybe we should add comments to each field of the struct as well?
- [x] `OutgoingRequest` (struct)
   - Maybe we should add comments to each field of the struct as well?
- [x] `IncomingService` (trait):
   - Should we document the expected behavior of `handle_request`?
- [x] `OutgoingService` (trait):
   - Should we document the expected behavior of `send_request`?
- [x] BoxedIlpFuture (type)
- [x] `AccountStore` (trait):
   - Should we document each function's expected output? Their names are pretty self-explanatory.
- [x] `incoming_service_fn` / `outgoing_service_fn`
- [x] `ServiceFn`
- [x] `WrappedService`: 
   - (nit) we can rename the generic parameters for the `wrap_incoming` and `wrap_outgoing` functions to be `I` and `O` for consistency, instead of `IO`
- [x] `AddressStore`: 
   - Should be filled to explain why this functionality is needed/used, short explanation: when a parent account is added the node's address must be updated to reflect the address assigned to it by the parent

**Comment by emschwartz** [comment]
This is going to have some serious breaking changes (or potentially be removed) based on #434 #142 #85

**Comment by bstrie** [comment]
If we did replace the services with Tower, I imagine we'd still want this crate around to provide IncomingRequest, OutgoingRequest, and Account.

**Comment by bstrie** [comment]
Should AddressStore be defined in interledger-packet, where Address is defined?

**Comment by emschwartz** [comment]
> Should AddressStore be defined in interledger-packet, where Address is defined?

No. `interledger-packet` is just the (de)serialization format.

**Comment by gakonst** [comment]
Maybe we can remove the `mut` requirement from services, as @kincaidoneil pointed out:

> Alternatively... why does handle_request on the service interface require a mutable borrow? Could we change it to just &self?
> (It seems like the CCP service is the only one that requires mutation, but we could update that with a Arc & Mutex or something) So it turns out not even CCP does. Am I missing something? Can we replace that without any other issues?

**Comment by bstrie** [comment]
If we're not sure why that function is `&mut self` then I'd say it's worth a try to remove it, if only to see whether it causes any problems (assuming that we don't actually need mutability anywhere, then it should be entirely painless to go from `&mut self` to `&self`). But I forget the broader context of the conversation, was there something else that we were hoping to gain from this? Something like, say, loosening up some other bounds elsewhere?

**Comment by bstrie** [comment]
- if the `trace` module doesn't need to be exported, then don't export it. Reduce public surface area.
- `Account`/`AccountStore`: if the names are self-explanatory then don't worry about it.
- `IncomingRequest`/`OutgoingRequest`: comments on fields sounds good to me
- `IncomingService`/`OutgoingService`: if the behavior isn't self-explanatory, then it should be documented
- `WrappedService`: rename the parameters for consistency (though I seem to remember that this was already done?)

**Comment by gakonst** [comment]
- trace is no longer exported
- account / account-store have been thoroughly documented
- comments in `Request` fields have been added
-  Comments on `Service` types and their functions have been added
- WrappedService params are in a good spot
