### ISSUE TITLE
interledger-btp API review for v1.0-rc

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#570]
`interledger-btp` public items marked with x are documented. Non-exported items are not taken into account. Follows format from #561.

Part of #557.

- [x] `BtpAccount` (trait)
  - Should the trait functions also be documented? Seem a bit self explanatory from the name
- [x] `BtpStore` (trait)
- [x] `connect_client` (fn)
- [x] `connect_to_service_account` (fn)
- [x] `parse_btp_url` (fn)
   - Should this be removed? We do not use it anywhere, and just manually remove the `btp+` prefix here: https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-btp/src/client.rs#L63
- [x] `btp_service_as_filter` (fn)
  - This is documented, but the comment is outdated. Needs to be updated to show that it converts the provided btp service to a warp filter
- [x] `BtpOutgoingService` (struct)
- [x] `BtpService` (struct)

**Comment by bstrie** [comment]
- `parse_btp_url`: remove it if we can get away with it

**Comment by gakonst** [comment]
Yup it's been removed
