### ISSUE TITLE
interledger-ccp API review for v1.0-rc

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#571]
`interledger-ccp` public items marked with x are documented. Non-exported items are not taken into account. Follows format from #561.

Part of #557.

- [x] `CcpRoutingAccount` (trait)
- [x] `RouteManagerStore` (trait):
   - Should this be renamed to `CcpRoutingStore`? That would make it consistent with how the other Account/Store pairs are named.
- [x] `RoutingRelation`
- [x] `Mode`
   - We never use `Idle` mode. Should we remove Mode altogether and assume `Sync`? https://github.com/interledger/rfcs/pull/455 is closed and seems stale atm, so I am not sure what's the path towards CCP standardization
- [x] `RouteControlRequest`
   - Should `to_prepare` be implemented as `Prepare::from(src: RouteControlRequest)`?
- [x] `RouteProp`
   - Should we convert it to `pub(crate)`?
- [x] `CcpRouteManager` 
- [x] `CcpRouteManagerBuilder`: Does this need to be documented? Its fields are docuemnted, and given that it's a builder its functionality should be intuitive.

**Comment by bstrie** [comment]
- I'd say yes to the rename of `RouteManagerStore`.
- No opinion on `Mode`, do whatever seems most conservative.
- If `RouteProp` can be made `pub(crate)`, then absolutely. Reducing the public surface area is good.
- `CcpRouteManagerBuilder`: Even just a line saying something like "See documentation on fields" would be nice to show that documentation wasn't just forgotten about.

**Comment by gakonst** [comment]
- Renamed to `CcpRoutingStore`
- `Mode` has been left as is, for potential future implementation of the `Idle` feature, since it's implemented in the js connectors
- `RouteProp` is now `pub(crate)`
- Added a small comment on `CcpRouteManagerBuilder`
