### ISSUE TITLE
interledger-http API review for v1.0-rc

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#574]
interledger-http public items marked with `x` are documented. Non-exported items are not taken into account. Follows format from #561. 

Part of #557.

- [x] `HttpAccount` (trait)
- [x] `HttpStore` (trait)
- [x] `deserialize_json` (fn)
- [x] `HttpServer` (struct)
   - `as_filter()`: Should we put some docs on the exact API endpoints this exposes or point to the spec?
- [x] `HttpClientService` (struct)
   - Maybe document that `send_request` serializes (& oer encodes) the ILP packet before sending it to the next service?
- [x] `error` (module)
   - Should we extract this to a separate crate? Seems generic enough, we discussed this another time.

**Comment by bstrie** [comment]
- `as_filter`: give a brief summary but link to the spec

**Comment by gakonst** [comment]
Yup, it does that right now: https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-http/src/server.rs#L111. The used `ilp_over_http` method underneath also has details on how it works https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-http/src/server.rs#L63
