### ISSUE TITLE
interledger-stream API review for v1.0-rc

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#575]
interledger-stream public items marked with `x` are documented. Non-exported items are not taken into account. Follows format from #561. 

Part of #557.

- [x] StreamDelivery (struct)
- [x] `send_money` (fn)
- [x] `SendMoneyFuture` (struct)
  - Not public, but its implementation and fields must be documented in detail since it's our main low-level payments protocol and may be a prime target for future optimizations etc.
- [x] `Error` (enum)
  - Do we need this? It's only imported in the SPSP Error wrapper enum, but that variant does not seem to get hit ever
- [x] `ConnectionGenerator` (struct)
- [x] `PaymentNotification (struct)
- [x] `StreamNotificationStore` (trait)
- [x] `StreamReceiverService` (struct)

**Comment by bstrie** [comment]
- `Error`: not sure if this was already addressed in the error overhaul, but if we don't need it then let's get rid of it

**Comment by gakonst** [comment]
Not sure why I had written this bullet initially, the error type is actually used within stream
