### ISSUE TITLE
Error Handling Improvements

### ISSUE THREAD

**Issue by ekrenzke** [interledger-rs/interledger-rs#58]
Hi everybody, I started some work on improving error handling in another WIP branch [here](https://github.com/emschwartz/interledger-rs/tree/ek-error-handling).

# Motivation
I began working on some tests, but found it hard to test some error cases. In an attempt to improve the creation of tests, I took it upon myself to improve error handling in the process.

# Implementation
Due to the layered nature of ILP, I thought it would be useful to formally define the types of errors that could occur within each layer for each crate. The error handling and propagation scheme looks roughly like this:

![error_handling](https://user-images.githubusercontent.com/11590210/55112683-7db6a280-50b3-11e9-8b2e-117e9da3f30d.png)
_edit: I meant `InvalidPacket` and `UnexpectedPacket` in the diagram above..._

Furthermore, each layer of the protocol is restricted to only emitting errors to the layer directly below it. Since no ILP packet handling is done explicitly at the BTP layer, I thought this made sense. Does anybody have different opinions on this?

Since the protocol stack is roughly ranked from bottom to top as: BTP, ILP, STREAM, SPSP, I thought it was appropriate to only allow the layers to communicate errors to the layer immediately beneath. (e.g. STREAM can propagate errors to ILP, which can be propagated to BTP, and handled at that layer.)

For now, I am purposefully omitting BTP Error packets and ILP Error packets, because the builder interface seems more appropriate for naming purposes, but it _does_ seem to lead to some slight inconsistency. Should these cases be handled in the module-level error handling case described above?

Higher-level (sub)protocols and interfaces are still able to utilize error types found in these crates by importing the appropriate error. (e.g. `use ilp::Error as IlpError`)

# Notes
This is also intended to reduce error handling dependencies. I think this is a more reasonable approach since each layer of the protocol is split into crates, therefore error types for each layer should be explicitly defined.

____
Let me know if you have any thoughts, concerns, or ideas, before I proceed.

**Comment by emschwartz** [comment]
The changes in that branch look good so far!

> Furthermore, each layer of the protocol is restricted to only emitting errors to the layer directly below it. 

I'm not totally sure what you mean by this.

> For now, I am purposefully omitting BTP Error packets and ILP Error packets, because the builder interface seems more appropriate for naming purposes, but it does seem to lead to some slight inconsistency.

I think that's fine. ILP Reject packets are slightly different because of the need to set the right error code. I wouldn't worry about the BTP stuff _too much_ because I think we're likely to move more in the HTTP direction anyway.

> Higher-level (sub)protocols and interfaces are still able to utilize error types found in these crates by importing the appropriate error. (e.g. use ilp::Error as IlpError)

:+1: 

> This is also intended to reduce error handling dependencies. I think this is a more reasonable approach since each layer of the protocol is split into crates, therefore error types for each layer should be explicitly defined.

Do you mean dependencies on crates like `quick_error` and `failure`? Arguably, the errors are already explicitly defined but maybe not consistently located, named, or formatted across all the crates, right?

**Comment by ekrenzke** [comment]
> The changes in that branch look good so far!
Thanks! It's a pretty quick and dirty attempt that will hopefully improve.
 
> > Furthermore, each layer of the protocol is restricted to only emitting errors to the layer directly below it.
> 
> I'm not totally sure what you mean by this.

Sorry, this is poorly worded.

My justification for restricting error handling to the immediately below the current layer can be summarized as an early return, and simplifies flow control. If an error occurs in STREAM, it can be propagated to ILP from STREAM, and then propagated to BTP from ILP.

If an error occurs in BTP, I do not think it makes sense to propagate the error to ILP, but I could be convinced otherwise. This is partly to eliminate potential feedback loops, but maybe Rust handles this? Basically, if an error occurs in parsing BTP, you cannot create an ILP Packet, and the same goes for ILP to STREAM. Am I wrong here?

> > For now, I am purposefully omitting BTP Error packets and ILP Error packets, because the builder interface seems more appropriate for naming purposes, but it does seem to lead to some slight inconsistency.
> 
> I think that's fine. ILP Reject packets are slightly different because of the need to set the right error code. I wouldn't worry about the BTP stuff _too much_ because I think we're likely to move more in the HTTP direction anyway.

Sounds good to me!

> Do you mean dependencies on crates like `quick_error` and `failure`? 

Yep. Let me know if you're opposed to this.

> Arguably, the errors are already explicitly defined but maybe not consistently located, named, or formatted across all the crates, right?

Yep, it has mostly to do with the inconsistency across different crates for me right now. Creating these errors from scratch does introduce significant amount of verbosity, but my personal preference is to keep libraries as close to `std` as possible. By explicit, I mean that you can only throw error types which are specified in the `Error` enum. This, in combination with a unilateral error flow allows for simple backtracing in debugging and testing.

Example:

```
[error(stream)] <msg> throwing to ilp
[ilp] attempting to resolve error that was passed...
[error(ilp)] <msg> throwing to btp
[btp] attempting to resolve error that was passed...
[error(btp)]: <msg>
```

**Comment by emschwartz** [comment]
> My justification for restricting error handling to immediately below the current layer can be summarized as an early return, and simplifies flow control. If an error occurs in STREAM, it can be propagated to ILP from STREAM, and then propagated to BTP from ILP.

I think I'm not quite clear on what you mean about how the errors will be propagated. Could you give me an example?

> Creating these errors from scratch does introduce significant amount of verbosity, but my personal preference is to keep libraries as close to std as possible.

Sounds good.

> By explicit, I mean that you can only throw error types which are specified in the Error enum.

Are there places where that isn't the case now?

**Comment by ekrenzke** [comment]
> > My justification for restricting error handling to immediately below the current layer can be summarized as an early return, and simplifies flow control. If an error occurs in STREAM, it can be propagated to ILP from STREAM, and then propagated to BTP from ILP.
> 
> I think I'm not quite clear on what you mean about how the errors will be propagated. Could you give me an example?
> 

Suppose you receive a request and need to create a response. You start by parsing the BTP packet, then extracting the ILP/STREAM packet. If you encounter an error in STREAM, you can handle it in the STREAM module, or you can throw an ILP error which can be handled there, or another error might be thrown to the BTP module for further error handling.

For parsing errors like `InvalidPacket` and `UnexpectedPacket`, the packet would just be dropped to avoid feedback loops on the network, as defined in the RFCs. However, logs could be improved by logging the cause of such errors, and how they propagate through the protocol stack. You could track where the error originated, and if you were able to construct a lower-level response.

If an error occurs in STREAM, maybe you still want to construct a BTP response that tells the requester that they sent a message that you cannot handle at the STREAM level. 

If an error occurs in BTP, there's no point in parsing anything in the layers above. You only handle the errors that are at the layer of the error origin or below. You should be able to map a STREAM error to an ILP error and an ILP error to a BTP error, but it should not be possible to map a BTP error to an SPSP error for example.

My mental model of Interledger is one where lower-level protocols are not aware of any protocols that are built on top of it. An application is aware of the transport, but the transport is not aware of the application layer.

> > By explicit, I mean that you can only throw error types which are specified in the Error enum.
> 
> Are there places where that isn't the case now?

Yes. In the STREAM module, `Utf8Error`s, `FromUtf8Error`, and others can still occur in `stream/packet.rs`, despite not being defined in [`error.rs`](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-stream/src/error.rs). This is because `stream/packet.rs` uses the `interledger_packet::ParseError` module. Instead, I am advocating for all error types for a module to be enumerated to avoid potential ambiguity. If an `io::Error` occurs in STREAM in the current version, it might look like it originated in the `interledger_packet` module if you're not careful. Granted, it would still say that it panicked at `line X` in the STREAM module, but this is just an attempt to remove any ambiguity.

**Comment by emschwartz** [comment]
> My mental model of Interledger is one where lower-level protocols are not aware of any protocols that are built on top of it. An application is aware of the transport, but the transport is not aware of the application layer.

That's correct

> In the STREAM module, Utf8Errors, FromUtf8Error, and others can still occur in stream/packet.rs, despite not being defined in error.rs

That's because those errors are handled automatically and never exposed to the user of the stream crate. The stream crate only needs to have errors in its enum that can actually be seen by the person who imports and uses that crate.

> This is because stream/packet.rs uses the interledger_packet::ParseError module.

Actually the real issue here is that the OER (de)serialization and the ParseError should probably be separated into a different crate that's used by each of the protocol crates.

> If an error occurs in STREAM, maybe you still want to construct a BTP response that tells the requester that they sent a message that you cannot handle at the STREAM level.

This shouldn't ever happen. BTP errors only apply if you've sent something invalid at that layer. If you do, it'll never make it to the STREAM receiver. If an error occurs in STREAM, it will either be sent back to the STREAM sender as an encrypted STREAM packet in an ILP F99 reject packet or certain errors are sent back with different ILP error codes.

As I said, the changes you've made thus far look good. I'm still not sure about the vision for the relationship between the errors from different protocol layers though

**Comment by ekrenzke** [comment]
> This shouldn't ever happen. BTP errors only apply if you've sent something invalid at that layer. If you do, it'll never make it to the STREAM receiver. If an error occurs in STREAM, it will either be sent back to the STREAM sender as an encrypted STREAM packet in an ILP F99 reject packet or certain errors are sent back with different ILP error codes.
> 
> As I said, the changes you've made thus far look good. I'm still not sure about the vision for the relationship between the errors from different protocol layers though

Noted. Propagating errors down the stack does not seem necessary then, and I will make the necessary adjustments. I was thinking that ILP would behave similarly to how something at the transport layer might throw an error to the networking layer in the OSI model.

**Comment by emschwartz** [comment]
It can but in really specific circumstances. I don't think it's necessary to make the translation of one protocol layer's error to another's automatic because they don't necessarily map 1:1. Take a look [here](https://github.com/emschwartz/interledger-rs/blob/es-redis/crates/interledger-stream/src/server.rs#L171-L180) and [here](https://github.com/emschwartz/interledger-rs/blob/es-redis/crates/interledger-stream/src/server.rs#L227-L247) for two examples of where the STREAM module specifically creates an ILP error (reject packet) to send back.

**Comment by emschwartz** [comment]
Superseded by https://github.com/interledger-rs/interledger-rs/issues/317
