### ISSUE TITLE
Add endpoint to adjust tracing level

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#586]
Currently we initialize `tracing` with whatever log level is given via the `RUST_LOG` env variable. It'd be nice if we had one more [admin API endpoint](https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-api/src/routes/node_settings.rs), at `/tracing-level` which would allow the node operator to modify it. 

- https://docs.rs/tracing-subscriber/0.2.0-alpha.4/tracing_subscriber/reload/index.html method to change the tracing level
- probably outdated since it's commented out, example from docs https://github.com/tokio-rs/tracing/blob/master/examples/examples/tower-load.rs#L40-L41

**Comment by matdehaast** [comment]
This would be really handy as usually I don't want to bounce the process to debug an issue

**Comment by dora-gt** [comment]
Hmmm I’m not sure if we want to set the level after launching nodes. Isn’t it sufficient to modify `RUST_LOG`? Do you want to **after launching**? @matdehaast

**Comment by gakonst** [comment]
Yes, this is for modifyign the log levels after the node has been launched, without having to restart the node.
