### ISSUE TITLE
ko-stream-reliability

### ISSUE THREAD

**Issue by beertastic** [interledger-rs/interledger-rs#648]
the tutorial here:
https://interledger.org/spin-up-local-network.html

Says to use the stream 'ko-stream-reliability'
but that donesn't exist... know what it means, or what the alternative is?

**Comment by kincaidoneil** [comment]
Sorry about that, I'll update it! If you just use `docker pull interledgerrs/ilp-node` instead of building from the branch, it should work.

**Comment by beertastic** [comment]
Ah, while you're there, there's a few links that go to 404 pages.
If you need a list, I'll happily provide

Great site otherwise! I've learnt heaps today!!
