### ISSUE TITLE
Try out gh actions docker build & push by tag pushing

### ISSUE THREAD

**Issue by pradovic** [interledger-rs/interledger-rs#678]
In order to test the gh actions docker build & push for `ilp-node` I am planning to tag the `master` with `ilp-node-testver-0.0.1`. This should trigger docker build & push for `ilp-node` and `testnet` with this custom version.

NOTE: This looks a bit ugly and we will not repeat it in the future, but we need it as a test case in the process of moving circleci flow go github actions, as the docker circleci step is currently broken.

**Comment by koivunej** [comment]
The annotated tag didn't create a bidi linking nor is it working from this page but the first one was: https://github.com/interledger-rs/interledger-rs/releases/tag/ilp-node-testver-0.0.1

**Comment by pradovic** [comment]
@koivunej Can we close this one?

**Comment by koivunej** [comment]
Yeah sure. dockerhub works now.
