### ISSUE TITLE
Create IlpAsset type

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#73]
Similar to the `IlpAddress` type from #69, it might be a good idea to define a new type, `IlpAsset`, which contains `str: asset_code` (or even better have some enum with defined assets, as well as `u8: asset_scale` which is well defined per asset.

**Comment by emschwartz** [comment]
Interesting idea! How would you describe the main benefits of adding such a type?

One issue I see with having an enum of assets is that different connections / accounts may use a different `asset_scale` for the same asset code. That said, if there are a couple places throughout the codebase that involve converting the asset scales so it wouldn't be terrible to centralize that logic.

**Comment by emschwartz** [comment]
@gakonst can this issue be closed now?
