### ISSUE TITLE
RUSTSEC-2020-0159: migration from chrono

### ISSUE THREAD

**Issue by koivunej** [interledger-rs/interledger-rs#737]
[RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159) means there should be an investigation into migrating to `time`. Some parts of the current timestamp parsing in the -packet, or -stream should be extra carefully verified against the respective interledger RFC's as there might not be good existing test cases.

**Comment by koivunej** [comment]
Marking this as `good-first-issue` for quite limited scope and easy discoverability (follow chrono dependencies). The scope includes multiple crates, but test case examples should exist wherever there is parsing code.

**Comment by pinkforest** [comment]
There is now new version of chrono we marked as patched
https://github.com/rustsec/advisory-db/pull/1306
The new version has pure rust version of localtime_r :partying_face: 
You might want to bump your Cargo.lock for it

**Comment by koivunej** [comment]
@pinkforest thanks for letting me know!

**Comment by pinkforest** [comment]
@koivunej  thanks for the response :purple_heart:  

Would you have time to roll a release to crates.io so we can point peeps to the new release potentially ?

Re: maintenance: https://github.com/interledger-rs/interledger-rs/issues/745

Could we also bump up the unicase dep? re: https://github.com/interledger-rs/interledger-rs/pull/744

Cheers

**Comment by koivunej** [comment]
I can handle the Cargo.lock updates because I have should still have write access, but I cannot update crates.io. Even if I could, I would probably just yank the existing releases re: #687 as this repo's output is only used as binary as far as I know rather than the many interconnected library crates.

I'll reply you over at #745 over the maintainership, possibly later.

**Comment by pinkforest** [comment]
Sweet - @emschwartz seems to have the crates.io access

**Comment by koivunej** [comment]
chrono got updated in #747, so closing this. unicase is still pending.
