### ISSUE TITLE
Rename Interledger.rs?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#81]
This project could use a catchier name and one that rolls off the tongue better than "Interledger dot r s". Anyone have suggestions?

**Comment by tarcieri** [comment]
First thing that came to my mind was some play on "Iron Bank" (e.g. Braavos)

**Comment by ekrenzke** [comment]
I was calling my zmq implementation "Mantle" but I have not had the bandwidth to work on it much lately. 

I am a big fan of double meanings. From Google:

1. an important role or responsibility that passes from one person to another.

2. the region of the earth's interior between the crust and the core, believed to consist of hot, dense silicate rocks (mainly peridotite).

The downside being "Mantle" is arguably used too often in software engineering.

**Comment by emschwartz** [comment]
Another option to throw into the mix: "Alloy" (metal theme + mixing different things and making them all stronger + flowing liquid to go along with streaming payments)

**Comment by gakonst** [comment]
What stainless alloys exist?

Since the language is Rust, we may want some theme around not being oxidised/corroded (corroded = bad code/unmaintained), around a "stainless alloy + liquid" mix?

**Comment by tarcieri** [comment]
Stainless steel is an alloy, FWIW...

**Comment by matdehaast** [comment]
Forge

**Comment by dora-gt** [comment]
`Poseidon` Inspired by...

- When once the ILP gets spread all over the world, money will be moving fast like a rapid current of water.
- It seems like a big ocean of money.
- Poseidon controls all the seas, `Interledger.rs` does.
- Crustaceans swim in the seas😂

**Comment by bstrie** [comment]
Since Rust's name is, obviously, based on [the fungus](https://en.wikipedia.org/wiki/Rust_(fungus)), I propose we take a page from biology. In particular fungal colonies are connected by underground *networks* named [mycelium](https://en.wikipedia.org/wiki/Mycelium), which is a bit of a mouthful, but a punchy synonym for "mycelium" is **shiro**, which rolls off the tongue nicely. :)

**Comment by emschwartz** [comment]
A friend made the point that Interledger.rs (or Interledger Rust) is the clearest regarding what it is. Other names might be more fun but don't contain as much information, especially for new people about what this project actually does. Worth considering

**Comment by emschwartz** [comment]
Thank you everyone for the suggestions! I think we're going to keep this project as Interledger.rs for now. While it doesn't roll off the tongue that nicely and I appreciate the humor of a bunch of the suggestions, I think it's most important to prioritize clarity and "Interledger.rs" or "Interledger Rust" most clearly describes what this is.
