### ISSUE TITLE
Switch to async/await syntax once stabilized 

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#85]
https://boats.gitlab.io/blog/post/await-decision-ii/

> I’m working actively on drafting a stabilization report to propose stabilizing a minimum viable version of async/await in the 1.37 release of Rust. 1.37 will be released in mid-August, and branches on July 4.

Once that's out, we should get a PR that replaces all the futures handling with async/await calls.

**Comment by bstrie** [comment]
Blocked on #142. Also note that async/await syntax has since been confirmed for Rust 1.38, releasing on September 26.
