### ISSUE TITLE
Make repo more Open Source friendly

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#88]
- Add contributing / PR / issues templates
- Currently each crate has no documentation, and there's no clear description on why/where/when they are used.

Nice guide from gitcoin: https://medium.com/gitcoin/how-to-build-a-contributor-friendly-project-927037f528d9

**Comment by gakonst** [comment]
@emschwartz do you have any Issue / PR template you'd want to add, or should we close this?

**Comment by emschwartz** [comment]
Issue and PR templates don't seem like a terrible idea but I don't have a particular template in mind. If you think it's not needed at this point, we can close this issue
