### ISSUE TITLE
Enforce trait bounds on struct declarations of services 

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#98]
Currently the `Store`s and the `next` fields of services are declared just with a generic parameter, and are later constrained only in their `impl` blocks. There are places where only a certain type of store would make sense, e.g. `HTTPStore` for `HTTPService`. Also a few services are accepted to only be outgoing or incoming.

e.g.:

https://github.com/emschwartz/interledger-rs/blob/es-settlement/crates/interledger-service-util/src/balance_service.rs#L43-L48

could be made to:
```rust
pub struct BalanceService<S: BalanceStore, O: OutgoingService<A>, A: IldcpAccount> {
    ilp_address: Bytes,
    store: S,
    next: O,
    account_type: PhantomData<A>,
}
```

and with [rfc2089](https://github.com/rust-lang/rfcs/blob/master/text/2089-implied-bounds.md
) that would remove the need for writing the bounds on each `impl` block.

extra ref:
https://stackoverflow.com/questions/49229332/should-trait-bounds-be-duplicated-in-struct-and-impl
https://users.rust-lang.org/t/should-i-put-where-bounds-on-the-struct-or-on-the-impl/7064/5

**Comment by gakonst** [comment]
On second thought this might be a bad idea since a lot of trait bounds will need to be specified in functions all over the code.

**Comment by emschwartz** [comment]
Can this be closed now?

**Comment by gakonst** [comment]
Yes. Recently read how this can be an anti-pattern, although I forget the reference.
